import { def, slide } from './builder';

// Definições literais de 03-graphs-set-theory.pdf ("N de 60"), dado em 02/09.
const S = (page: number, title: string) => slide('03-graphs-set-theory.pdf', page, title);

export const conjuntosDefinitions = [
  def({
    id: 'conjunto',
    topic: 'teoria-de-conjuntos',
    concept: 'conjunto e elemento',
    definition:
      'Conjunto: coleção "bem-definida" (e não-ordenada) de objetos. Elemento: cada objeto do conjunto é denominado de elemento ou membro. Notação: A = {melão, laranja, morango}; melão ∈ A; uva ∉ A.',
    keyPoints: ['Coleção BEM-DEFINIDA de objetos', 'NÃO-ORDENADA', 'Cada objeto é um elemento/membro; notação ∈ / ∉'],
    intuition: 'Saco de coisas: não importa a ordem nem quantas vezes você diz o nome de algo — {a, a, b} = {b, a}. "Bem-definida" = dá para decidir sem ambiguidade se algo está dentro ou fora.',
    example: 'Slide 4: conjunto vazio ({} ou ∅) = conjunto dos dinossauros vivos.',
    source: S(3, 'Definição de conjuntos'),
  }),
  def({
    id: 'igualdade-de-conjuntos',
    topic: 'teoria-de-conjuntos',
    concept: 'igualdade de conjuntos',
    definition: 'Dois conjuntos são ditos iguais sse eles possuem os mesmos elementos. Formalmente, A = B significa (∀x)[(x ∈ A → x ∈ B) ∧ (x ∈ B → x ∈ A)], ou A = B ↔ ∀x : (x ∈ A ↔ x ∈ B).',
    keyPoints: ['Iguais sse têm os MESMOS elementos', 'Formal: ∀x (x ∈ A ↔ x ∈ B)', 'Ordem e repetição não importam'],
    intuition: 'Mesmo conteúdo, mesmo conjunto. O slide mostra {a, b, c, d} = {d, a, c, b} = {a, a, a, b, b, c, d}. Para provar A = B, mostra-se A ⊆ B e B ⊆ A.',
    source: S(7, 'Igualdade de conjuntos'),
  }),
  def({
    id: 'subconjunto',
    topic: 'teoria-de-conjuntos',
    concept: 'subconjunto (A ⊆ B)',
    definition: 'O conjunto A é dito um subconjunto de B (A ⊆ B) sse todo elemento de A é também um elemento de B. Formalmente, A ⊆ B significa ∀x : (x ∈ A → x ∈ B).',
    keyPoints: ['Notação A ⊆ B', 'TODO elemento de A está em B', 'Formal: ∀x (x ∈ A → x ∈ B)'],
    intuition: 'Caixa dentro da caixa: tudo que está em A também está em B. Todo conjunto é subconjunto de si mesmo, e ∅ é subconjunto de todos. Cuidado (slide 8): {A} ⊆ B não é o mesmo que A ⊆ B.',
    source: S(8, 'Subconjuntos'),
  }),
  def({
    id: 'subconjunto-proprio',
    topic: 'teoria-de-conjuntos',
    concept: 'subconjunto próprio (A ⊂ B)',
    definition: 'A é um subconjunto próprio de B (A ⊂ B) sse cada elemento de A estiver em B e pelo menos um elemento de B não está em A.',
    keyPoints: ['Notação A ⊂ B', 'A ⊆ B', 'E existe pelo menos um elemento de B que NÃO está em A (A ≠ B)'],
    intuition: 'Subconjunto "de verdade": está dentro e é estritamente menor. ⊆ permite igualdade; ⊂ não. (O slide 11 do deck 05 usa V1 ⊂ V para subgrafo — mesma ideia de "está contido".)',
    examLikelihood: 'medium',
    source: S(8, 'Subconjuntos'),
  }),
  def({
    id: 'conjunto-potencia',
    topic: 'teoria-de-conjuntos',
    concept: 'conjunto potência P(A)',
    definition: 'Dado um conjunto A, o conjunto potência de A, denotado por P(A), é o conjunto formado por todos os subconjuntos de A. Ex.: A = {1, 2, 3} ⇒ P(A) = {∅, {1}, {2}, {3}, {1, 2}, {1, 3}, {2, 3}, {1, 2, 3}}; P(∅) = {∅}.',
    keyPoints: ['Notação P(A)', 'Conjunto de TODOS os subconjuntos de A', 'Inclui ∅ e o próprio A; |P(A)| = 2^|A|'],
    intuition: 'Todas as maneiras de escolher ou não cada elemento: 2 opções por elemento ⇒ 2ⁿ subconjuntos. É o mesmo raciocínio de "quantos subgrafos" (escolher ou não cada aresta).',
    example: 'Slide 13: P(∅) = {∅} — tem um elemento (o vazio), não é vazio.',
    source: S(13, 'Conjunto potência'),
  }),
  def({
    id: 'cardinalidade',
    topic: 'teoria-de-conjuntos',
    concept: 'cardinalidade |X|',
    definition:
      'Cardinalidade de X: número de elementos em um conjunto X. A cardinalidade de X é denotada por |X|; |{2, 5, 7}| = 3. Um conjunto é dito contável se for o conjunto correspondente a alguma sequência (seus elementos podem ser arranjados em uma lista ordenada e contados); todos os conjuntos finitos são contáveis; um conjunto que não é contável é dito incontável.',
    keyPoints: ['Número de elementos; notação |X|', 'Contável: elementos podem ser listados em sequência', 'Finito ⇒ contável; não contável = incontável'],
    intuition: '"Quantos tem?" É a mesma barra que usamos em |V| = n e |E| = m nos grafos — cardinalidade do conjunto de vértices e de arestas.',
    source: S(15, 'Cardinalidade de conjuntos'),
  }),
  def({
    id: 'produto-cartesiano',
    topic: 'teoria-de-conjuntos',
    concept: 'produto cartesiano A × B',
    definition: 'O produto cartesiano de dois conjuntos A e B é o conjunto de todos os pares ordenados (a, b), onde a ∈ A e b ∈ B, ou seja: A × B = {(a, b) | a ∈ A ∧ b ∈ B}.',
    keyPoints: ['Conjunto de todos os PARES ORDENADOS (a, b)', 'a ∈ A e b ∈ B', '|A × B| = |A| · |B|'],
    intuition: 'Tabela com uma linha por elemento de A e uma coluna por elemento de B: cada célula é um par. É exatamente onde vive E de um grafo direcionado: E ⊆ V × V ("relação binária em V").',
    example: 'Slide 17: A = {1, 2}, B = {a, b, c} ⇒ A × B = {(1, a), (1, b), (1, c), (2, a), (2, b), (2, c)}.',
    source: S(17, 'Produto cartesiano'),
  }),
  def({
    id: 'conjunto-universo',
    topic: 'teoria-de-conjuntos',
    concept: 'conjunto universo U',
    definition: 'Conjunto universo (conjunto universal): o conjunto que contém "todas as coisas", denominado U, que contém todos os objetos para os quais a discussão faz sentido.',
    keyPoints: ['Denominado U', 'Contém TODOS os objetos relevantes para a discussão', 'É o referencial do complemento Ā'],
    intuition: 'O "mundo" onde os conjuntos vivem — o mesmo papel do universo de discurso na lógica de predicados. Sem U, "complemento de A" não tem sentido.',
    examLikelihood: 'medium',
    source: S(18, 'Conjunto universo'),
  }),
  def({
    id: 'uniao-de-conjuntos',
    topic: 'teoria-de-conjuntos',
    concept: 'união de conjuntos (A ∪ B)',
    definition: 'União: A ∪ B = {x ∈ U | x ∈ A ∨ x ∈ B}. x ∈ A ∪ B ↔ x ∈ A ∨ x ∈ B.',
    keyPoints: ['Notação A ∪ B', 'Elementos que estão em A OU em B (ou em ambos)', 'Corresponde ao conectivo ∨'],
    intuition: 'Juntar os dois sacos num só (sem duplicar). Cada operação de conjunto espelha um conectivo lógico: ∪ ↔ ∨, ∩ ↔ ∧, complemento ↔ ¬.',
    source: S(19, 'Operações sobre conjuntos'),
  }),
  def({
    id: 'intersecao-de-conjuntos',
    topic: 'teoria-de-conjuntos',
    concept: 'interseção de conjuntos (A ∩ B)',
    definition: 'Interseção: A ∩ B = {x ∈ U | x ∈ A ∧ x ∈ B}. x ∈ A ∩ B ↔ x ∈ A ∧ x ∈ B.',
    keyPoints: ['Notação A ∩ B', 'Elementos que estão em A E em B', 'Corresponde ao conectivo ∧'],
    intuition: 'O que os dois sacos têm em comum. Se não têm nada, A ∩ B = ∅ (disjuntos).',
    source: S(19, 'Operações sobre conjuntos'),
  }),
  def({
    id: 'diferenca-de-conjuntos',
    topic: 'teoria-de-conjuntos',
    concept: 'diferença de conjuntos (A − B)',
    definition: 'Diferença: A − B = {x ∈ U | x ∈ A ∧ x ∉ B}. x ∈ A − B ↔ x ∈ A ∧ x ∉ B. Identidade (slide 20): A − B = A ∩ B̄.',
    keyPoints: ['Notação A − B', 'Elementos que estão em A E NÃO estão em B', 'A − B = A ∩ B̄'],
    intuition: 'Tira de A tudo que também está em B. É a operação que usamos ao definir complemento de grafo: E(Ḡ) = E(Kn) − E(G).',
    note: 'O slide 19 imprime "x ∈ A ∨ x ∉ B" na diferença — provável erro de digitação; a identidade A − B = A ∩ B̄ (slide 20) e o diagrama confirmam que é "∧" (está em A E não está em B).',
    source: S(19, 'Operações sobre conjuntos'),
  }),
  def({
    id: 'complemento-de-conjunto',
    topic: 'teoria-de-conjuntos',
    concept: 'complemento de um conjunto (Ā)',
    definition: 'Complemento: Ā = {x ∈ U | x ∉ A}. x ∈ Ā ↔ x ∉ A.',
    keyPoints: ['Notação Ā', 'Tudo em U que NÃO está em A', 'Corresponde a ¬'],
    intuition: 'O "resto do mundo" fora de A. Mesma ideia (e mesma barra) do grafo complementar Ḡ: as arestas que faltam.',
    example: 'Slide 20: A ∩ Ā = ∅; A ∪ Ā = U; complemento duplo: Ā̄ = A.',
    source: S(19, 'Operações sobre conjuntos'),
  }),
  def({
    id: 'conjuntos-disjuntos',
    topic: 'teoria-de-conjuntos',
    concept: 'conjuntos disjuntos e mutuamente disjuntos',
    definition:
      'Dois conjuntos são chamados disjuntos sse eles não têm nenhum elemento em comum: A e B são disjuntos ↔ A ∩ B = ∅. Os conjuntos A1, A2, …, An são chamados mutuamente disjuntos (ou disjuntos par-a-par) sse Ai ∩ Aj = ∅ para todos i, j = 1, …, n com i ≠ j.',
    keyPoints: ['Disjuntos: A ∩ B = ∅', 'Mutuamente disjuntos: Ai ∩ Aj = ∅ para TODO par i ≠ j'],
    intuition: 'Sem nada em comum. É a condição da bipartição (V1 e V2 disjuntos) e dos subgrafos "disjuntos de vértices/arestas" do deck 05.',
    source: S(21, 'Conjuntos disjuntos'),
  }),
  def({
    id: 'particao',
    topic: 'teoria-de-conjuntos',
    concept: 'partição de um conjunto',
    definition: 'Uma coleção de conjuntos não vazios {A1, A2, …, An} é uma partição (de A) sse A = A1 ∪ A2 ∪ … ∪ An e A1, A2, …, An são mutuamente disjuntos.',
    keyPoints: ['Conjuntos NÃO VAZIOS', 'A união deles é o conjunto todo (A)', 'São MUTUAMENTE DISJUNTOS'],
    intuition: 'Fatiar o bolo: todo pedaço tem alguma coisa, os pedaços não se sobrepõem e juntos formam o bolo inteiro. "Particionar V em V1 e V2" (bipartido) e "componentes conexos" são partições.',
    source: S(21, 'Conjuntos disjuntos — Partição'),
  }),
  def({
    id: 'de-morgan-conjuntos',
    topic: 'teoria-de-conjuntos',
    concept: 'leis de De Morgan (conjuntos)',
    prompt: 'Enuncie as leis de De Morgan para conjuntos.',
    definition: 'De Morgan: complemento de (A ∩ B) = Ā ∪ B̄; complemento de (A ∪ B) = Ā ∩ B̄.',
    keyPoints: ['(A ∩ B)‾ = Ā ∪ B̄', '(A ∪ B)‾ = Ā ∩ B̄', 'Complementar troca ∩ por ∪ (e vice-versa)'],
    intuition: 'Mesma lei da lógica traduzida: ¬(p ∧ q) ⇔ ¬p ∨ ¬q vira (A ∩ B)‾ = Ā ∪ B̄. "Não estar nos dois" = "não estar em pelo menos um".',
    source: S(20, 'Identidades de conjuntos'),
  }),
  def({
    id: 'funcao',
    topic: 'teoria-de-conjuntos',
    concept: 'função',
    definition:
      'Sejam A e B conjuntos não-vazios. Uma função f de A para B é uma associação de exatamente um elemento de B a cada elemento de A. Escreve-se f(a) = b se b for o único elemento de B associado por meio de f ao elemento a de A. Notação f : A → B.',
    keyPoints: ['A e B não-vazios', 'A CADA elemento de A associa EXATAMENTE UM elemento de B', 'f(a) = b; notação f : A → B'],
    intuition: 'Máquina determinística: entra a, sai sempre o mesmo b. Cada entrada tem uma saída, e só uma. (Um elemento de B pode receber vários a — isso é permitido.)',
    example: 'Slide 26: f(x) = 2, f(y) = 4, f(z) = 2 ⇒ f = {(x, 2), (y, 4), (z, 2)}.',
    source: S(24, 'Funções: uma introdução'),
  }),
  def({
    id: 'dominio-contradominio-imagem',
    topic: 'teoria-de-conjuntos',
    concept: 'domínio, contra-domínio, imagem e imagem inversa',
    prompt: 'Para f : A → B, defina domínio, contra-domínio, imagem e imagem inversa (slide 25).',
    definition:
      'Domínio: o conjunto A é chamado de domínio de f. Contra-domínio: o conjunto B é chamado de co-domínio ou contra-domínio de f. Imagem: a imagem de f é o conjunto de valores que f pode assumir: {b ∈ B | b = f(a) para algum a ∈ A}. Imagem inversa: a imagem inversa (ou inversa) de um elemento b ∈ B é o conjunto de valores de a ∈ A que são mapeados a b via f: {a ∈ A | f(a) = b}.',
    keyPoints: ['Domínio = A (entradas)', 'Contra-domínio = B (saídas possíveis)', 'Imagem = {f(a)} ⊆ B (saídas que realmente ocorrem)', 'Imagem inversa de b = {a | f(a) = b}'],
    intuition: 'Domínio: de onde parte. Contra-domínio: para onde PODERIA ir. Imagem: para onde realmente vai. Imagem inversa de b: quem cai em b. No slide 26, imagem = {2, 4}, contra-domínio = {1, 2, 3, 4}, inversa de 2 = {x, z}.',
    source: S(25, 'Funções: uma introdução'),
  }),
  def({
    id: 'funcao-injetora',
    topic: 'teoria-de-conjuntos',
    concept: 'função injetora',
    definition:
      'Uma função f : A → B é uma função injetora (ou injetiva ou um-para-um) se e somente se para todos a1, a2 ∈ A: a1 ≠ a2 → f(a1) ≠ f(a2). Uma função é dita injetora se cada elemento do domínio é mapeado para um elemento diferente do contra-domínio.',
    keyPoints: ['a1 ≠ a2 ⇒ f(a1) ≠ f(a2) (ou: f(a1) = f(a2) ⇒ a1 = a2)', 'Elementos diferentes do domínio vão para elementos DIFERENTES', 'Também chamada injetiva / um-para-um'],
    intuition: 'Sem colisão: dois inputs diferentes nunca dão o mesmo output. Cada b recebe no máximo uma seta. É a metade do "um-para-um" da definição de isomorfismo.',
    example: 'Slide 29: f(x) = x + 1 é injetora; f(x) = (x − 1)(x − 2) não é (f(1) = f(2) = 0).',
    source: S(29, 'Função injetora'),
  }),
  def({
    id: 'funcao-sobrejetora',
    topic: 'teoria-de-conjuntos',
    concept: 'função sobrejetora',
    definition:
      'Uma função f : A → B é uma função sobrejetora (ou sobrejetiva) se e somente se para todo b ∈ B há a ∈ A de forma que f(a) = b. Uma função é dita sobrejetora se cada elemento do contra-domínio é imagem de pelo menos um elemento do domínio.',
    keyPoints: ['Para TODO b ∈ B existe a ∈ A com f(a) = b', 'Imagem = contra-domínio', 'Cada b recebe PELO MENOS uma seta'],
    intuition: 'Ninguém em B fica sem visita: toda saída possível é atingida por alguma entrada. Sobrejetora = "cobre B inteiro".',
    example: 'Slide 30 (f : R → R): f(x) = x + 1 é sobrejetora; f(x) = x² não é (nunca dá negativo).',
    source: S(30, 'Função sobrejetora'),
  }),
  def({
    id: 'funcao-bijetora',
    topic: 'teoria-de-conjuntos',
    concept: 'função bijetora',
    definition: 'Uma função f : A → B é uma função bijetora se e somente se ela é sobrejetora e injetora.',
    keyPoints: ['Injetora E sobrejetora', 'Cada b recebe EXATAMENTE uma seta'],
    intuition: 'Correspondência perfeita: cada a tem seu b único e cada b tem seu a único. É a "correspondência um-para-um" da definição de isomorfismo e o que permite definir a inversa.',
    example: 'Slide 31 (f : R → R): x + 1 e x/10 são bijetoras; 2x (nos inteiros, não sobrejetora) e (x−1)(x−2) não são.',
    source: S(31, 'Função bijetora'),
  }),
  def({
    id: 'funcao-inversa',
    topic: 'teoria-de-conjuntos',
    concept: 'função inversa f⁻¹',
    definition: 'Seja f : A → B uma função bijetora. A função inversa de f, denotada por f⁻¹ : B → A, é tal que f⁻¹(y) = x sse y = f(x).',
    keyPoints: ['Só existe se f é BIJETORA', 'f⁻¹ : B → A (sentido contrário)', 'f⁻¹(y) = x ⟺ f(x) = y'],
    intuition: 'Desfazer a máquina. Precisa de bijetora: injetora garante que não há ambiguidade (um y vem de um único x), sobrejetora garante que todo y tem de onde voltar.',
    example: 'Slide 32: f(x) = x + 1 em N ⇒ f⁻¹(x) = x − 1; f(x) = x² em R não é inversível (f(1) = f(−1)).',
    source: S(32, 'Função inversa'),
  }),
  def({
    id: 'composicao-de-funcoes',
    topic: 'teoria-de-conjuntos',
    concept: 'composição de funções (f ∘ g)',
    definition:
      'Sejam g : A → B′ e f : B → C funções tais que a imagem de g é um subconjunto do domínio de f (B′ ⊆ B). A função composta de f com g, denotada por f ∘ g : A → C, é definida para todo a ∈ A por (f ∘ g)(a) = f(g(a)). A função f ∘ g é chamada de composição de f e g.',
    keyPoints: ['Exige imagem de g ⊆ domínio de f', 'Notação f ∘ g : A → C', '(f ∘ g)(a) = f(g(a)) — aplica g PRIMEIRO, depois f'],
    intuition: 'Duas máquinas em série: a saída de g vira entrada de f. Lê-se de dentro para fora — f ∘ g é "g, depois f". Em geral f ∘ g ≠ g ∘ f (slide 34: n + 1 e n² dão (n²) + 1 vs (n + 1)²).',
    source: S(33, 'Composição de funções'),
  }),
];
