import { def, slide } from './builder';

// Definições literais de 06-graphs-propositional-logic.pdf ("N de 38") e
// 07-graphs-predicate-logic.pdf ("N de 39"). Dadas em 03/09 e 09/09 —
// imediatamente antes da P1 (cronograma 2026/2).
const P = (page: number, title: string) => slide('06-graphs-propositional-logic.pdf', page, title);
const Q = (page: number, title: string) => slide('07-graphs-predicate-logic.pdf', page, title);

export const logicaDefinitions = [
  // ---------------- Lógica proposicional ----------------
  def({
    id: 'logica',
    topic: 'logica-proposicional',
    concept: 'lógica',
    definition:
      'Lógica: ramo da Filosofia, Matemática e Ciência da Computação que trata das inferências válidas. A lógica estuda a preservação da verdade durante uma argumentação: hipóteses verdadeiras → conclusões verdadeiras.',
    keyPoints: ['Trata das INFERÊNCIAS VÁLIDAS', 'Estuda a PRESERVAÇÃO DA VERDADE numa argumentação (hipóteses V ⇒ conclusões V)'],
    intuition: 'Lógica não diz o que é verdade; diz como não perder a verdade no caminho. Se você parte de coisas verdadeiras e segue as regras, chega em coisas verdadeiras — é isso que uma prova matemática usa.',
    examLikelihood: 'medium',
    source: P(3, 'Princípios da Lógica Proposicional'),
  }),
  def({
    id: 'assercao',
    topic: 'logica-proposicional',
    concept: 'asserção',
    definition: 'Asserção: uma declaração (afirmação, sentença declarativa).',
    keyPoints: ['Declaração / sentença DECLARATIVA', '(perguntas e ordens não são asserções)'],
    intuition: 'Qualquer frase que AFIRMA algo. "x > 5" é asserção (afirma), "Você fala francês?" não é (pergunta). Asserção é mais larga que proposição — nem toda asserção tem valor V/F definido.',
    example: 'Slide 4: "x > 5" e "Esta declaração é falsa" são asserções, mas não proposições.',
    examLikelihood: 'medium',
    source: P(4, 'Proposições Lógicas'),
  }),
  def({
    id: 'proposicao',
    topic: 'logica-proposicional',
    concept: 'proposição',
    definition:
      'Proposição: uma asserção que é verdadeira (V) ou falsa (F), mas não ambos. (Slide 5: uma sentença declarativa — que estabelece um fato — que pode ser verdadeira ou falsa, mas não ambos.)',
    keyPoints: ['É uma ASSERÇÃO (sentença declarativa)', 'Tem valor verdadeiro OU falso', 'NÃO ambos'],
    intuition:
      'Frase que dá para julgar: ou é V ou é F, sem meio-termo e sem depender de variável solta. "2 + 3 = 5" é proposição (V). "x > 5" não é (depende de x). "Esta declaração é falsa" não é (paradoxo — nem V nem F).',
    example: 'Slide 5: "Belo Horizonte é a capital de Minas Gerais" (proposição V); "Que horas são?" (não é proposição).',
    source: P(4, 'Proposições Lógicas'),
  }),
  def({
    id: 'valor-verdade',
    topic: 'logica-proposicional',
    concept: 'valor verdade',
    definition: 'Valor verdade: o resultado da avaliação de uma proposição (V ou F).',
    keyPoints: ['Resultado da AVALIAÇÃO de uma proposição', 'Só dois valores: V ou F'],
    intuition: 'A "nota" da proposição: V ou F. Tabela verdade é só uma tabela de valores verdade para todas as combinações possíveis.',
    examLikelihood: 'medium',
    source: P(4, 'Proposições Lógicas'),
  }),
  def({
    id: 'variaveis-proposicionais',
    topic: 'logica-proposicional',
    concept: 'variáveis proposicionais',
    definition: 'Em Lógica, as proposições podem ser denotadas por símbolos, tais como p, q, r, …, os quais são chamados de variáveis proposicionais.',
    keyPoints: ['Símbolos p, q, r, … que denotam proposições'],
    intuition: 'Apelidos curtos para frases inteiras: p = "o Sol está brilhando hoje". Assim as fórmulas ficam legíveis (p ∧ q) em vez de frases gigantes.',
    example: 'Slide 6: p: o Sol está brilhando hoje; q: 2 + 3 = 5.',
    examLikelihood: 'medium',
    source: P(6, 'Variáveis Proposicionais'),
  }),
  def({
    id: 'negacao',
    topic: 'logica-proposicional',
    concept: 'negação (¬p)',
    definition:
      'Negação: a sentença "Não é verdade que p" é uma outra proposição, chamada de a negação de p. Notação: ¬p, ∼p, not p. Se p é verdadeiro, então ¬p é falso; se p é falso, então ¬p é verdadeiro.',
    keyPoints: ['"Não é verdade que p" é uma NOVA proposição', 'Notação ¬p (ou ∼p, not p)', 'Inverte o valor verdade: p V ⇒ ¬p F; p F ⇒ ¬p V'],
    intuition: 'Interruptor: liga vira desliga. É o único operador de UMA proposição só — por isso o slide 11 o chama de "operador", e reserva "conectivo" para os que juntam duas.',
    example: 'Slide 8: p: 2 + 3 > 1; ¬p: 2 + 3 ≤ 1.',
    source: P(8, 'Tabela Verdade — Negação'),
  }),
  def({
    id: 'conectivos',
    topic: 'logica-proposicional',
    concept: 'conectivos lógicos (vs. operador negação)',
    prompt: 'Diferencie o operador negação dos conectivos lógicos, conforme o slide 11.',
    definition:
      'Operador negação: constrói uma nova proposição a partir de uma única proposição existente. Conectivos: operadores lógicos usados para formar novas proposições a partir de duas ou mais proposições já existentes.',
    keyPoints: ['Negação: opera sobre UMA proposição', 'Conectivos: formam nova proposição a partir de DUAS OU MAIS'],
    intuition: 'Negação é unária (um só input); conectivos (∧ ∨ ⊕ → ↔) são binários (dois inputs). Os cinco conectivos + a negação são todas as ferramentas da lógica proposicional.',
    examLikelihood: 'medium',
    source: P(11, 'Conectivos Lógicos'),
  }),
  def({
    id: 'conjuncao',
    topic: 'logica-proposicional',
    concept: 'conjunção (p ∧ q)',
    definition: 'Conjunção (operação "e"): notação p ∧ q, "p e q", "p and q". Definição pela tabela verdade: p ∧ q é V somente quando p e q são ambos V; F nos demais casos.',
    keyPoints: ['Operação "e"', 'Notação p ∧ q', 'V SÓ quando p e q são ambos V'],
    intuition: 'Duas chaves em série: a luz só acende se AS DUAS estiverem ligadas. Uma falsa derruba tudo.',
    example: 'Slide 12: p: hoje é terça-feira; q: está chovendo hoje; p ∧ q: hoje é terça-feira e está chovendo hoje.',
    source: P(11, 'Conectivos Lógicos'),
  }),
  def({
    id: 'disjuncao',
    topic: 'logica-proposicional',
    concept: 'disjunção (p ∨ q)',
    definition: 'Disjunção (operação "ou inclusivo"): notação p ∨ q, "p ou q", "p or q". Definição pela tabela verdade: p ∨ q é F somente quando p e q são ambos F; V nos demais casos.',
    keyPoints: ['Operação "ou INCLUSIVO"', 'Notação p ∨ q', 'F SÓ quando p e q são ambos F (V se pelo menos um é V)'],
    intuition: 'Duas chaves em paralelo: acende se QUALQUER uma (ou as duas) estiver ligada. "Inclusivo" = os dois juntos também contam como V — diferente do "ou" do cardápio ("arroz ou batata").',
    source: P(11, 'Conectivos Lógicos'),
  }),
  def({
    id: 'disjuncao-exclusiva',
    topic: 'logica-proposicional',
    concept: 'disjunção exclusiva (p ⊕ q)',
    definition: 'Disjunção exclusiva (operação "xor"): notação p ⊕ q, "p xor q", "p ou q (mas não ambos)". V quando exatamente um dos dois é V.',
    keyPoints: ['Operação "xor"', 'Notação p ⊕ q', 'V quando EXATAMENTE UM dos dois é V (F se ambos V ou ambos F)'],
    intuition: 'O "ou" do cardápio: arroz OU batata, não os dois. Verdadeiro quando p e q DISCORDAM.',
    source: P(13, 'Principais Conectivos Lógicos'),
  }),
  def({
    id: 'condicional',
    topic: 'logica-proposicional',
    concept: 'condicional / implicação (p → q)',
    definition:
      'Condicional ou implicação (se p, então q): notação p → q. V quando p e q são ambos V, ou quando p é F (não importando q); F somente quando p é V e q é F. p é chamada de hipótese, antecedente ou premissa; q é chamada de conclusão ou consequente.',
    keyPoints: ['"Se p, então q"; notação p → q', 'F SÓ quando p é V e q é F', 'p é F ⇒ p → q é V, não importa q', 'p = hipótese/antecedente/premissa; q = conclusão/consequente'],
    intuition:
      'Promessa (slide 18): "se eu for eleito, abaixo os impostos". Só quebrei a promessa se fui eleito E não abaixei. Se não fui eleito, a promessa não foi quebrada — vale (V) faça eu o que fizer. "Uma falsa hipótese implica em qualquer conclusão."',
    example: 'Slide 20: "Se 2 + 2 = 5, então no Brasil não há corrupção" é V (hipótese falsa).',
    source: P(14, 'Principais Conectivos Lógicos — Condicional'),
  }),
  def({
    id: 'formas-do-condicional',
    topic: 'logica-proposicional',
    concept: 'formas de expressar p → q',
    prompt: 'Liste as formas de expressar a implicação p → q em linguagem natural (slide 15).',
    definition: 'Formas de expressar p → q: "se p, então q"; "p é condição suficiente para q"; "q é condição necessária para p"; "p somente se q"; "q é consequência lógica de p".',
    keyPoints: ['se p, então q', 'p é condição SUFICIENTE para q', 'q é condição NECESSÁRIA para p', 'p SOMENTE SE q', 'q é consequência lógica de p'],
    intuition:
      'Suficiente vs necessário confunde todo mundo: "fogo é necessário para fumaça" = "se há fumaça, então há fogo" (fumaça → fogo). O que vem DEPOIS do → é o necessário; o que vem ANTES é o suficiente. "p somente se q" também é p → q (não o contrário!).',
    example: 'Slide 16: "Fogo é uma condição necessária para fumaça" ⇒ antecedente "há fumaça", consequente "há fogo".',
    source: P(15, 'O Condicional'),
  }),
  def({
    id: 'converso-inverso-contrapositiva',
    topic: 'logica-proposicional',
    concept: 'converso, inverso e contrapositiva de p → q',
    prompt: 'Defina o converso, o inverso e a contrapositiva de p → q.',
    definition: 'Se p → q é uma condicional, então: o converso de p → q é a implicação q → p; o inverso de p → q é a implicação ¬p → ¬q; a contrapositiva de p → q é a implicação ¬q → ¬p.',
    keyPoints: ['Converso: q → p', 'Inverso: ¬p → ¬q', 'Contrapositiva: ¬q → ¬p', '(só a contrapositiva é equivalente a p → q)'],
    intuition:
      '"Se Murilo é mineiro, é brasileiro." Converso troca os lados (brasileiro → mineiro: falso!). Inverso nega os dois (não mineiro → não brasileiro: falso!). Contrapositiva troca E nega (não brasileiro → não mineiro: verdadeiro — e sempre equivale à original, slide 30).',
    example: 'Slide 21: p: Murilo é mineiro; q: Murilo é brasileiro.',
    source: P(21, 'O Condicional'),
  }),
  def({
    id: 'bicondicional',
    topic: 'logica-proposicional',
    concept: 'bicondicional / equivalência (p ↔ q)',
    definition:
      'Bicondicional ou equivalência (p → q ∧ q → p): notação p ↔ q. V somente quando p e q têm o mesmo valor verdade. Formas de expressar: "p se, e somente se, q"; "p é necessário e suficiente para q"; "se p então q, e conversamente".',
    keyPoints: ['É (p → q) ∧ (q → p)', 'Notação p ↔ q', 'V SÓ quando p e q têm o MESMO valor verdade', '"se e somente se" / "necessário e suficiente"'],
    intuition: 'Implicação nos dois sentidos ao mesmo tempo. É o oposto do xor: V quando p e q CONCORDAM. "sse" é a abreviação que aparece em todo o slide de conjuntos.',
    example: 'Slide 23: "3 > 2 se e somente se 0 < 3 − 2" é V (ambos V).',
    source: P(22, 'Principais Conectivos Lógicos — Bicondicional'),
  }),
  def({
    id: 'proposicao-composta',
    topic: 'logica-proposicional',
    concept: 'proposição composta',
    definition:
      'Proposições compostas: podem ter muitas partes componentes, cada parte sendo uma sentença representada por alguma variável proposicional. Estas proposições são construídas com o auxílio dos conectivos lógicos.',
    keyPoints: ['Formada por partes (variáveis proposicionais)', 'Construída com CONECTIVOS lógicos'],
    intuition: 'Lego: peças (p, q, r) encaixadas por conectivos. O valor verdade da composta é calculado de dentro para fora, respeitando parênteses e precedência.',
    example: 'Slide 24: r : p → [q ∧ (p → q)].',
    examLikelihood: 'medium',
    source: P(24, 'Proposições Compostas'),
  }),
  def({
    id: 'tabela-verdade',
    topic: 'logica-proposicional',
    concept: 'tabela verdade',
    definition:
      'Tabela verdade: fornece os valores verdade de uma proposição composta em termos dos valores verdade de suas partes componentes. Construção (slide 28): as primeiras n colunas são as variáveis proposicionais; sob elas listam-se os 2ⁿ possíveis conjuntos de valores verdade; para cada linha, computam-se os valores restantes (colunas intermediárias).',
    keyPoints: ['Dá o valor verdade da composta para CADA combinação das partes', 'n variáveis ⇒ 2ⁿ linhas', 'Colunas intermediárias para as subexpressões, depois a expressão final'],
    intuition: 'Testar todos os cenários possíveis, sem exceção. Com 3 variáveis são 8 mundos possíveis; se em todos a coluna final dá V, é tautologia; se em todos dá F, contradição.',
    example: 'Slide 29: (p ∨ q) → (r ↔ p) com 8 linhas e colunas intermediárias p ∨ q e r ↔ p.',
    source: P(9, 'Tabela Verdade'),
  }),
  def({
    id: 'ordem-de-precedencia',
    topic: 'logica-proposicional',
    concept: 'ordem de precedência dos operadores lógicos',
    prompt: 'Qual é a ordem de precedência dos operadores lógicos (slide 25)?',
    definition: 'Em uma expressão composta, a ordem de aplicação (precedência) dos operadores é: 1. negação ¬; 2. conjunção ∧; 3. disjunção ∨; 4. implicação →; 5. implicação dupla ↔.',
    keyPoints: ['1º ¬', '2º ∧', '3º ∨', '4º →', '5º ↔'],
    intuition: 'Igual a aritmética: ¬ é o "sinal de menos" (cola no que vem depois), ∧ é a multiplicação, ∨ é a soma, → e ↔ vêm por último. Na dúvida, use parênteses.',
    example: 'Slide 25: p ∨ ¬q ∧ r equivale a p ∨ ((¬q) ∧ r); p → q ∨ r equivale a p → (q ∨ r).',
    source: P(25, 'Ordem de precedência'),
  }),
  def({
    id: 'tautologia',
    topic: 'logica-proposicional',
    concept: 'tautologia',
    definition: 'Tautologia: proposição que é sempre V (para todas as possíveis situações). Exemplo: p ∨ ¬p.',
    keyPoints: ['SEMPRE V', 'Em TODAS as situações (todas as linhas da tabela verdade)'],
    intuition: '"Vai chover ou não vai chover" — verdade garantida, não importa o mundo. Uma tautologia não dá informação, mas é o que define equivalência lógica (p ↔ q tautologia).',
    source: P(31, 'Classificação de Proposições Compostas'),
  }),
  def({
    id: 'contradicao',
    topic: 'logica-proposicional',
    concept: 'contradição (absurdo)',
    definition: 'Contradição (ou absurdo): proposição que é sempre F (em todas as possíveis situações). Exemplo: p ∧ ¬p.',
    keyPoints: ['SEMPRE F', 'Em TODAS as situações', 'Também chamada de absurdo'],
    intuition: '"Está chovendo e não está chovendo" — impossível em qualquer mundo. Chegar numa contradição é o que fecha uma prova por absurdo.',
    source: P(31, 'Classificação de Proposições Compostas'),
  }),
  def({
    id: 'contingencia',
    topic: 'logica-proposicional',
    concept: 'contingência',
    definition: 'Contingência: proposição que pode ser V ou F, dependendo dos valores verdade de suas variáveis proposicionais. Nem tautologia nem contradição.',
    keyPoints: ['Pode ser V ou F conforme as variáveis', 'NEM tautologia NEM contradição'],
    intuition: 'O caso normal: a tabela verdade tem V em algumas linhas e F em outras. "p ∧ q" é contingência.',
    source: P(31, 'Classificação de Proposições Compostas'),
  }),
  def({
    id: 'equivalencia-logica',
    topic: 'logica-proposicional',
    concept: 'equivalência lógica (p ⇔ q)',
    definition: 'Se p ↔ q é uma tautologia, as proposições p e q são ditas logicamente equivalentes. Notação: p ⇔ q. Se p ⇔ q, os dois lados são simplesmente diferentes modos de construir a mesma sentença.',
    keyPoints: ['p ↔ q é uma TAUTOLOGIA', 'Notação p ⇔ q (seta dupla grossa, diferente de ↔)', 'Mesma coluna na tabela verdade em todas as linhas'],
    intuition: 'Duas frases que dizem a mesma coisa de jeitos diferentes: em todo cenário, ou as duas são V ou as duas são F. Verifica-se por tabela verdade (slide 33) ou pelas leis (slide 34).',
    example: 'Slide 30: (p → q) ⇔ (¬q → ¬p).',
    source: P(32, 'Equivalência lógica'),
  }),
  def({
    id: 'de-morgan-logica',
    topic: 'logica-proposicional',
    concept: 'leis de De Morgan (lógica proposicional)',
    prompt: 'Enuncie as leis de De Morgan para a lógica proposicional.',
    definition: 'Leis de De Morgan: ¬(p ∧ q) ⇔ ¬p ∨ ¬q; ¬(p ∨ q) ⇔ ¬p ∧ ¬q.',
    keyPoints: ['¬(p ∧ q) ⇔ ¬p ∨ ¬q', '¬(p ∨ q) ⇔ ¬p ∧ ¬q', 'Negar troca ∧ por ∨ (e vice-versa) e nega cada parte'],
    intuition:
      '"Não é verdade que o rio é raso OU poluído" = "o rio NÃO é raso E NÃO é poluído" (slide 35). A negação entra distribuindo e vira o conectivo ao contrário. A mesma lei vale para conjuntos (∩/∪) e quantificadores (∀/∃).',
    example: 'Slide 35: ¬(p ∨ q) ≠ "o rio não é raso OU não é poluído".',
    source: P(34, 'Algumas Equivalências importantes'),
  }),

  // ---------------- Lógica de predicados ----------------
  def({
    id: 'predicado',
    topic: 'logica-de-predicados',
    concept: 'predicado / função proposicional P(x)',
    definition:
      'A declaração "x é maior do que 3" tem duas partes: a variável x (o "sujeito") e "é maior do que 3" (o "predicado"). O predicado é uma propriedade que o sujeito da declaração pode ter. Denotamos por P(x): P é o predicado, x é a variável; P(x) é o valor da função proposicional P em x. Uma vez que um valor tenha sido atribuído a x, P(x) se torna uma proposição e tem um valor verdade.',
    keyPoints: ['Predicado = PROPRIEDADE que o sujeito (variável) pode ter', 'Notação P(x): P predicado, x variável', 'P(x) é uma função proposicional — vira PROPOSIÇÃO quando x recebe valor'],
    intuition: 'Frase com lacuna: "___ é maior do que 3". Enquanto a lacuna está vazia, não dá para julgar V/F. Preencha (P(4)) e vira proposição (V). Com mais lacunas: Q(x, y), R(x, y, z).',
    example: 'Slide 5: P(x): x > 3 ⇒ P(4) é V, P(2) é F.',
    source: Q(4, 'Predicados'),
  }),
  def({
    id: 'universo-de-discurso',
    topic: 'logica-de-predicados',
    concept: 'universo de discurso (domínio)',
    definition: 'Universo de discurso (ou domínio): o conjunto que especifica os possíveis valores da variável x. O valor verdade de uma declaração quantificada frequentemente depende de quais elementos estão neste universo de discurso.',
    keyPoints: ['Especifica os POSSÍVEIS VALORES da variável', 'O valor verdade de ∀x/∃x DEPENDE dele'],
    intuition: 'De quem estamos falando? "∀x (x² ≥ x)" é V nos inteiros e F nos reais (slide 13: x = 0,5). Sem dizer o universo, a frase quantificada nem tem valor definido.',
    example: 'Slide 13: ∀x (x² ≥ x) — F nos reais, V nos inteiros.',
    source: Q(8, 'Quantificador Universal'),
  }),
  def({
    id: 'quantificador-universal',
    topic: 'logica-de-predicados',
    concept: 'quantificador universal (∀)',
    definition:
      'A quantificação universal de P(x) é a proposição: "P(x) é V para todos os valores de x no universo de discurso". Denotada por ∀x P(x) — "para todo x, P(x)". Quando o universo pode ser listado como x1, …, xn, ∀x P(x) equivale à conjunção P(x1) ∧ P(x2) ∧ … ∧ P(xn).',
    keyPoints: ['∀x P(x): P(x) é V para TODOS os x do universo', 'Lê-se "para todo x, P(x)"', 'Universo finito: equivale à CONJUNÇÃO P(x1) ∧ … ∧ P(xn)', 'É F se existe UM x com P(x) F (contra-exemplo)'],
    intuition: '"Todo mundo aqui passou em Cálculo": basta UMA pessoa que não passou para a frase inteira ser F. ∀ é um "e" gigante sobre todos os elementos.',
    example: 'Slide 9: P(x): x + 1 > x nos reais ⇒ ∀x P(x) é V. Slide 10: Q(x): x < 2 nos reais ⇒ ∀x Q(x) é F (Q(3) é F).',
    source: Q(9, 'Quantificador Universal'),
  }),
  def({
    id: 'quantificador-existencial',
    topic: 'logica-de-predicados',
    concept: 'quantificador existencial (∃)',
    definition:
      'A quantificação existencial de P(x) é a proposição: "existe um elemento x no universo de discurso tal que P(x) é V". Notação: ∃x P(x) — "existe um x tal que P(x)", "existe pelo menos um x tal que P(x)", "para algum x, P(x)". Quando o universo pode ser listado, ∃x P(x) equivale à disjunção P(x1) ∨ P(x2) ∨ … ∨ P(xn).',
    keyPoints: ['∃x P(x): EXISTE (pelo menos um) x no universo com P(x) V', 'Lê-se "existe um x tal que P(x)" / "para algum x"', 'Universo finito: equivale à DISJUNÇÃO P(x1) ∨ … ∨ P(xn)', 'É F só se P(x) é F para TODO x'],
    intuition: '"Alguém aqui já foi a São Paulo": basta UMA pessoa para ser V. ∃ é um "ou" gigante sobre todos os elementos.',
    example: 'Slide 17: P(x): x > 3 nos reais ⇒ ∃x P(x) é V (x = 4). Q(x): x = x + 1 ⇒ ∃x Q(x) é F.',
    source: Q(15, 'Quantificador Existencial'),
  }),
  def({
    id: 'quantificadores-quando-v-f',
    topic: 'logica-de-predicados',
    concept: 'quando ∀x P(x) e ∃x P(x) são V ou F (resumo do slide 20)',
    prompt: 'Complete o resumo do slide 20: quando ∀x P(x) e ∃x P(x) são verdadeiros e quando são falsos?',
    definition: '∀x P(x): V quando P(x) é V para todo x; F quando existe um x para o qual P(x) é F. ∃x P(x): V quando existe um x para o qual P(x) é V; F quando P(x) é F para todo x.',
    keyPoints: ['∀ é V ⟺ P(x) V para todo x', '∀ é F ⟺ existe x com P(x) F', '∃ é V ⟺ existe x com P(x) V', '∃ é F ⟺ P(x) F para todo x'],
    intuition: 'Repare na simetria: o que torna ∀ FALSO (um x que falha) é a mesma forma do que torna ∃ VERDADEIRO (um x que funciona). É por isso que ¬∀ vira ∃¬.',
    source: Q(20, 'Quantificadores - Resumo'),
  }),
  def({
    id: 'contra-exemplo',
    topic: 'logica-de-predicados',
    concept: 'contra-exemplo',
    definition:
      'Para mostrar que uma declaração da forma ∀x P(x) é F, só é preciso encontrar um valor de x no universo de discurso para o qual P(x) é F; este valor é chamado de contra-exemplo da declaração ∀x P(x).',
    keyPoints: ['Serve para mostrar que ∀x P(x) é FALSA', 'É UM valor de x (no universo) com P(x) F', 'Um único basta'],
    intuition: 'Para derrubar um "todo", basta uma exceção. Nas provas de grafos é a mesma coisa: "todo grafo com X tem Y?" — desenhe UM grafo com X sem Y e acabou.',
    example: 'Slide 14: P(x): x² > 0 nos inteiros — x = 0 é contra-exemplo de ∀x P(x).',
    source: Q(14, 'Quantificador Universal'),
  }),
  def({
    id: 'variavel-ligada-livre',
    topic: 'logica-de-predicados',
    concept: 'variável ligada e variável livre',
    definition:
      'Quando um quantificador é usado sobre a variável x, ou quando atribuímos um valor a esta variável, dizemos que esta ocorrência da variável está ligada (ou "amarrada"). Uma ocorrência de variável que não está ligada a um quantificador ou fixa em um valor particular é chamada de variável livre. Todas as variáveis de uma função proposicional devem estar ligadas para que ela seja considerada uma proposição.',
    keyPoints: ['Ligada: sob um QUANTIFICADOR ou com VALOR atribuído', 'Livre: nem quantificada nem fixada', 'Só vira PROPOSIÇÃO quando todas as variáveis estão ligadas'],
    intuition: 'Lacuna preenchida (ligada) vs lacuna aberta (livre). "∃x Q(x, y)": x está amarrado pelo ∃, y está solto — a frase ainda não tem valor verdade.',
    example: 'Slide 24: em ∃x Q(x, y), x é ligada e y é livre.',
    source: Q(22, 'Ligando variáveis'),
  }),
  def({
    id: 'escopo-do-quantificador',
    topic: 'logica-de-predicados',
    concept: 'escopo de um quantificador',
    definition: 'A parte de uma expressão lógica à qual um quantificador é aplicado é o seu escopo. Uma variável é livre se estiver fora do escopo de todos os quantificadores na fórmula que a especifica.',
    keyPoints: ['Escopo = parte da expressão à qual o quantificador se APLICA', 'Variável fora de todo escopo é LIVRE'],
    intuition: 'Alcance do "para todo": até onde o ∀x manda. Em ∃x (P(x) ∧ Q(x)) ∨ ∀x R(x), o primeiro x vale só dentro do parêntese; o segundo, só em R(x) — podem até ser renomeados (∀y R(y)).',
    example: 'Slide 24: escopo de ∃x é P(x) ∧ Q(x); escopo de ∀x é R(x).',
    examLikelihood: 'medium',
    source: Q(23, 'Ligando variáveis'),
  }),
  def({
    id: 'negacao-de-quantificadores',
    topic: 'logica-de-predicados',
    concept: 'negação de quantificadores',
    prompt: 'Enuncie as equivalências de negação de quantificadores (slides 27–29).',
    definition: '¬∀x P(x) ≡ ∃x ¬P(x); ¬∃x Q(x) ≡ ∀x ¬Q(x).',
    keyPoints: ['¬∀x P(x) ≡ ∃x ¬P(x)', '¬∃x P(x) ≡ ∀x ¬P(x)', 'Negar troca ∀ por ∃ (e vice-versa) e nega o predicado'],
    intuition:
      '"Não é verdade que todo aluno fez Cálculo" = "existe aluno que NÃO fez". "Não existe político honesto" = "todo político é desonesto" (slide 30). É De Morgan para quantificadores: ∀ é um ∧ gigante, ∃ é um ∨ gigante.',
    example: 'Slide 32: ¬∀x (x² > x) ≡ ∃x (x² ≤ x).',
    source: Q(29, 'Negações - Resumo'),
  }),
  def({
    id: 'traducao-restricao-dominio',
    topic: 'logica-de-predicados',
    concept: 'tradução com restrição de domínio: → com ∀, ∧ com ∃',
    prompt: 'Ao ampliar o universo de discurso, qual conectivo acompanha ∀ e qual acompanha ∃ na tradução (slides 37 e 39)? Por quê?',
    definition:
      'Com universo "todas as pessoas" e E(x): "x é estudante desta turma": "todo estudante desta turma estudou Cálculo" é ∀x (E(x) → C(x)) — não ∀x (E(x) ∧ C(x)), pois isto significaria "todas as pessoas são estudantes nesta turma e já estudaram Cálculo". "Algum estudante desta sala já foi a São Paulo" é ∃x (E(x) ∧ S(x)) — não ∃x (E(x) → S(x)), pois para isto ser V bastaria ter alguém fora da sala.',
    keyPoints: ['∀ com restrição usa → : ∀x (E(x) → C(x))', '∃ com restrição usa ∧ : ∃x (E(x) ∧ S(x))', '∀ com ∧ afirma que TODOS são estudantes (errado)', '∃ com → fica V com alguém fora do grupo (errado)'],
    intuition:
      '∀ + ∧ é forte demais (obriga todo o universo a ter a propriedade de restrição); ∃ + → é fraco demais (qualquer não-estudante torna E(x) → S(x) V de graça). Regra de bolso: "todo … é …" ⇒ ∀→ ; "algum … é …" ⇒ ∃∧.',
    source: Q(37, 'Sentenças para lógica (um quantificador)'),
  }),
];
