/**
 * Pré-requisitos de cada definição (ids sem o prefixo `def-`): o que você
 * precisa entender ANTES para a definição fazer sentido. Vazio = dá para
 * aprender do zero, sabendo só o que é grafo, vértice e aresta. Forma um
 * DAG (teste garante que não há ciclo).
 */
export const PREREQUISITES: Record<string, string[]> = {
  // Fundamentos
  grafo: [],
  'vertice-aresta': [],
  'grafo-direcionado': ['grafo'],
  'grafo-nao-direcionado': ['grafo'],
  laco: ['vertice-aresta'],
  'arestas-paralelas': ['vertice-aresta'],
  'grafo-simples': ['laco', 'arestas-paralelas'],
  'vertices-adjacentes': ['vertice-aresta'],
  grau: ['vertice-aresta'],
  'grau-entrada-saida': ['grafo-direcionado', 'grau'],
  'laco-conta-duas-vezes': ['laco', 'grau'],
  'sequencia-de-graus': ['grau'],
  'arestas-adjacentes': ['vertice-aresta', 'arestas-paralelas'],
  'aresta-incidente': ['vertice-aresta'],
  'grafo-regular': ['grau'],
  'vertice-isolado': ['grau'],
  'vertice-pendente': ['grau'],
  'grafo-nulo': ['vertice-isolado'],
  'grafo-rotulado': ['grafo'],
  'grafo-valorado': ['grafo'],
  'grafo-completo': ['vertices-adjacentes', 'grafo-simples'],
  'tripartido-completo': ['bipartido-completo'],
  walk: ['vertice-aresta'],
  trail: ['walk'],
  path: ['trail'],
  cycle: ['path'],
  'grafo-conexo': ['path'],
  'grafo-bipartido': ['grafo', 'particao'],
  'bipartido-completo': ['grafo-bipartido', 'vertices-adjacentes'],
  'propriedade-de-grau': ['grau'],
  'teorema-grau-impar': ['propriedade-de-grau'],
  'uniao-de-grafos': ['grafo', 'uniao-de-conjuntos'],
  'soma-de-grafos': ['uniao-de-grafos'],
  'remocao-de-aresta': ['grafo'],
  'remocao-de-vertice': ['aresta-incidente'],
  'contracao-de-aresta': ['remocao-de-aresta', 'aresta-incidente'],
  // Representações
  'matriz-de-incidencia': ['grafo-direcionado', 'aresta-incidente'],
  'matriz-de-adjacencia': ['vertices-adjacentes', 'grafo-direcionado'],
  'lista-de-adjacencia': ['vertices-adjacentes'],
  'lista-de-predecessores': ['lista-de-adjacencia', 'grafo-transposto'],
  // Isomorfismo / subgrafo
  isomorfismo: ['aresta-incidente', 'funcao-bijetora'],
  'condicoes-necessarias-isomorfismo': ['isomorfismo', 'sequencia-de-graus', 'grafo-conexo'],
  'grafo-complementar': ['grafo-completo', 'grafo-simples'],
  'auto-complementar': ['grafo-complementar', 'isomorfismo'],
  subgrafo: ['subconjunto', 'grafo'],
  'subgrafo-induzido': ['subgrafo'],
  'propriedades-de-subgrafo': ['subgrafo'],
  'subgrafos-disjuntos-de-arestas': ['subgrafo', 'conjuntos-disjuntos'],
  'subgrafos-disjuntos-de-vertices': ['subgrafo', 'conjuntos-disjuntos'],
  'sequencia-de-arestas': ['aresta-incidente'],
  'caminho-slide-05': ['sequencia-de-arestas'],
  'caminho-aberto-fechado': ['caminho-slide-05'],
  cadeia: ['grafo-direcionado', 'caminho-slide-05'],
  'teorema-maximo-arestas': ['grafo-conexo', 'grafo-completo', 'grafo-simples'],
  'teorema-minimo-arestas': ['grafo-conexo'],
  // Busca / conectividade
  'busca-em-largura': ['vertices-adjacentes', 'grafo-conexo'],
  'busca-em-profundidade': ['vertices-adjacentes', 'grafo-conexo'],
  'fecho-transitivo-direto': ['grafo-direcionado', 'path', 'busca-em-profundidade'],
  'fecho-transitivo-inverso': ['fecho-transitivo-direto', 'grafo-transposto'],
  'grafo-transposto': ['grafo-direcionado'],
  base: ['fecho-transitivo-direto'],
  'anti-base': ['base', 'grafo-transposto'],
  'identificacao-de-base': ['base', 'grau-entrada-saida', 'contracao-de-aresta'],
  excentricidade: ['path', 'busca-em-largura'],
  raio: ['excentricidade'],
  diametro: ['excentricidade'],
  centro: ['raio'],
  'aresta-de-arvore': ['busca-em-profundidade'],
  'aresta-de-retorno': ['busca-em-profundidade', 'cycle'],
  'aresta-de-avanco': ['aresta-de-arvore'],
  'aresta-de-cruzamento': ['aresta-de-arvore'],
  'estados-dfs-ciclo': ['busca-em-profundidade', 'cycle', 'aresta-de-retorno'],
  'kosaraju-scc': ['busca-em-profundidade', 'grafo-transposto', 'path'],
  // Lógica proposicional
  logica: [],
  assercao: [],
  proposicao: ['assercao'],
  'valor-verdade': ['proposicao'],
  'variaveis-proposicionais': ['proposicao'],
  negacao: ['proposicao'],
  conectivos: ['negacao'],
  'tabela-verdade': ['valor-verdade'],
  conjuncao: ['conectivos', 'tabela-verdade'],
  disjuncao: ['conectivos', 'tabela-verdade'],
  'disjuncao-exclusiva': ['disjuncao'],
  condicional: ['conectivos', 'tabela-verdade'],
  'formas-do-condicional': ['condicional'],
  'converso-inverso-contrapositiva': ['condicional', 'negacao'],
  bicondicional: ['condicional', 'conjuncao'],
  'proposicao-composta': ['conectivos', 'variaveis-proposicionais'],
  'ordem-de-precedencia': ['proposicao-composta'],
  tautologia: ['tabela-verdade'],
  contradicao: ['tabela-verdade'],
  contingencia: ['tautologia', 'contradicao'],
  'equivalencia-logica': ['bicondicional', 'tautologia'],
  'de-morgan-logica': ['equivalencia-logica', 'conjuncao', 'disjuncao'],
  // Lógica de predicados
  predicado: ['proposicao'],
  'universo-de-discurso': ['predicado'],
  'quantificador-universal': ['predicado', 'universo-de-discurso', 'conjuncao'],
  'quantificador-existencial': ['predicado', 'universo-de-discurso', 'disjuncao'],
  'quantificadores-quando-v-f': ['quantificador-universal', 'quantificador-existencial'],
  'contra-exemplo': ['quantificador-universal'],
  'variavel-ligada-livre': ['quantificador-universal', 'quantificador-existencial'],
  'escopo-do-quantificador': ['variavel-ligada-livre'],
  'negacao-de-quantificadores': ['quantificador-universal', 'quantificador-existencial', 'negacao'],
  'traducao-restricao-dominio': ['quantificador-universal', 'quantificador-existencial', 'condicional', 'conjuncao'],
  // Conjuntos e funções
  conjunto: [],
  'igualdade-de-conjuntos': ['conjunto'],
  subconjunto: ['conjunto'],
  'subconjunto-proprio': ['subconjunto'],
  'conjunto-potencia': ['subconjunto'],
  cardinalidade: ['conjunto'],
  'produto-cartesiano': ['conjunto'],
  'conjunto-universo': ['conjunto'],
  'uniao-de-conjuntos': ['conjunto', 'disjuncao'],
  'intersecao-de-conjuntos': ['conjunto', 'conjuncao'],
  'diferenca-de-conjuntos': ['intersecao-de-conjuntos', 'complemento-de-conjunto'],
  'complemento-de-conjunto': ['conjunto-universo'],
  'conjuntos-disjuntos': ['intersecao-de-conjuntos'],
  particao: ['conjuntos-disjuntos', 'uniao-de-conjuntos'],
  'de-morgan-conjuntos': ['complemento-de-conjunto', 'uniao-de-conjuntos', 'intersecao-de-conjuntos'],
  funcao: ['conjunto'],
  'dominio-contradominio-imagem': ['funcao'],
  'funcao-injetora': ['funcao', 'dominio-contradominio-imagem'],
  'funcao-sobrejetora': ['funcao', 'dominio-contradominio-imagem'],
  'funcao-bijetora': ['funcao-injetora', 'funcao-sobrejetora'],
  'funcao-inversa': ['funcao-bijetora'],
  'composicao-de-funcoes': ['funcao', 'dominio-contradominio-imagem'],
};

/** Conceitos que são o ponto de partida absoluto — não têm "antes". */
export const ROOT_CONCEPTS = new Set(['grafo', 'vertice-aresta', 'logica', 'assercao', 'conjunto']);
