/* ===========================================================================
   CONTEUDO — prova1.js
   Banco de questoes da Prova 1: CLA/somador completo, ponto flutuante
   (IEEE754 customizado), Lei de Amdahl/speedup, CPI medio e desempenho, e
   questoes abertas. Carrega depois de content/factories.js.
   =========================================================================== */

const CLA_SOMADOR_REVIEW = [
  reviewMC({id:'rev_p1_cla_prop',category:'cla_somador',subtopic:'propagador',errorType:'CLA',quickRule:'Pi = Ai XOR Bi: propaga um carry que já existir.'},
    'No método de antecipação de carry (CLA), qual é a definição do bit propagador <b>Pi</b>?',
    ['Pi = Ai XOR Bi','Pi = Ai AND Bi','Pi = Ai OR NOT Bi','Pi = NOT(Ai) AND NOT(Bi)'],0,
    'O propagador indica que, se já existir um carry de entrada, ele passará adiante: Pi = Ai XOR Bi. Quando Pi=1, um carry de entrada vira carry de saída.'),
  reviewMC({id:'rev_p1_cla_gen',category:'cla_somador',subtopic:'gerador',errorType:'CLA',quickRule:'Gi = Ai AND Bi: gera carry sozinho, sem depender de Ci.'},
    'Qual é a definição do bit gerador <b>Gi</b> no CLA?',
    ['Gi = Ai AND Bi','Gi = Ai XOR Bi','Gi = Ai OR Bi','Gi = NOT(Ai XOR Bi)'],0,
    'Gi=1 quando os dois bits de entrada são 1: Ai AND Bi. Nessa posição, o carry de saída é gerado sozinho, sem depender do carry de entrada.'),
  reviewMC({id:'rev_p1_cla_carry_formula',category:'cla_somador',subtopic:'fórmula do carry',errorType:'CLA',quickRule:'Ci+1 = Gi + Pi·Ci.'},
    'Qual fórmula calcula corretamente o carry de saída <b>Ci+1</b> a partir de Pi, Gi e do carry de entrada Ci?',
    ['Ci+1 = Gi + (Pi · Ci)','Ci+1 = Gi · Pi · Ci','Ci+1 = Gi XOR Ci','Ci+1 = Pi + Ci'],0,
    'O carry sai por dois motivos: a posição gera carry sozinha (Gi) ou propaga um carry que já chegou (Pi·Ci). Por isso Ci+1 = Gi + Pi·Ci.'),
  reviewTF({id:'rev_p1_cla_gen_independente',category:'cla_somador',subtopic:'gerador independente',errorType:'CLA',quickRule:'Gi=1 garante carry de saída mesmo com Ci=0.'},
    'Se Gi = 1 em uma posição, o carry de saída dessa posição é 1 independente do valor do carry de entrada.',
    true,
    'Verdadeiro. Gi=1 significa Ai=Bi=1, o que já garante carry de saída 1 mesmo que Ci=0. É essa independência que permite calcular o CLA sem esperar a propagação bit a bit.'),
  reviewTF({id:'rev_p1_cla_no_gen_no_prop',category:'cla_somador',subtopic:'sem geração nem propagação',errorType:'CLA',quickRule:'Pi=Gi=0 força Ci+1=0.'},
    'Se Pi = 0 e Gi = 0 em uma posição, o carry de saída dessa posição será sempre 1.',
    false,
    'Falso. Pi=0 e Gi=0 significa Ai=Bi=0: não há geração nem propagação, então Ci+1 = 0 + 0·Ci = 0, sempre 0, independente do carry de entrada.'),
  reviewMC({id:'rev_p1_cla_fulladder_sum',category:'cla_somador',subtopic:'somador completo',errorType:'somador completo',quickRule:'Si = Ai XOR Bi XOR Ci.'},
    'Considere um somador completo (full adder) tradicional com entradas Ai, Bi e Ci. Qual expressão calcula corretamente a soma <b>Si</b>?',
    ['Si = Ai XOR Bi XOR Ci','Si = Ai AND Bi AND Ci','Si = Ai OR Bi OR Ci','Si = (Ai AND Bi) OR Ci'],0,
    'A soma de um bit é 1 quando um número ímpar das três entradas é 1 — exatamente a função XOR de três entradas: Si = Ai XOR Bi XOR Ci.'),
  reviewAR({id:'rev_p1_cla_ripple_sequencial',category:'cla_somador',subtopic:'ripple-carry',errorType:'somador completo',quickRule:'Ripple-carry: cada estágio espera o carry do anterior.'},
    '"Em um somador ripple-carry de N bits, o carry de cada estágio só pode ser calculado depois que o carry do estágio anterior estiver pronto, formando uma cadeia sequencial de atrasos."',
    true,
    'Verdadeiro. Essa dependência sequencial (o Cout de um estágio vira o Cin do próximo) faz o atraso total crescer com N no ripple-carry — motivo pelo qual o CLA existe: calcular os carries a partir de Pi e Gi sem esperar a cadeia inteira.'),
  reviewMC({id:'rev_p1_cla_freq_ripple4',category:'cla_somador',subtopic:'atraso e frequência',errorType:'somador completo',quickRule:'Atraso total do ripple-carry = nº de estágios × atraso por estágio; freq = 1/atraso.'},
    'Um somador completo gasta 2 ns entre o carry de entrada e o carry de saída (Cin → Cout) de um mesmo estágio. Em um somador ripple-carry de 4 bits, o carry se propaga estágio a estágio até o último bit. Qual a frequência máxima aproximada de operação, considerando apenas esse caminho crítico do carry?',
    ['125 MHz','500 MHz','250 MHz','62,5 MHz'],0,
    'O carry atravessa 4 estágios em cadeia, 2 ns cada: atraso total = 4 × 2 ns = 8 ns. A frequência máxima nesse caminho é F = 1/8ns = 125 MHz.')
];

const IEEE754_CUSTOM_REVIEW = [
  reviewMC({id:'rev_p1_float_bias',category:'ieee754_custom',subtopic:'bias',errorType:'ponto flutuante',quickRule:'Bias = 2^(bits do expoente - 1) - 1.'},
    'Em um formato de ponto flutuante customizado de 12 bits (1 sinal + 5 expoente + 6 mantissa), qual é o valor do bias (excesso) usado no expoente?',
    ['15','31','16','7'],0,
    'Com 5 bits de expoente, o bias é 2^(5-1) − 1 = 15. O expoente armazenado é o expoente real somado a esse bias.'),
  reviewMC({id:'rev_p1_float_decode',category:'ieee754_custom',subtopic:'conversão para decimal',errorType:'ponto flutuante',quickRule:'valor = (1+mantissa) × 2^(expoente armazenado − bias).'},
    'Nesse formato (1 sinal + 5 expoente + 6 mantissa, bias 15), um número está armazenado como <span class="mono">0 10000 100000</span>. Qual o valor decimal representado?',
    ['3,0','1,5','6,0','0,75'],0,
    'Sinal positivo. Expoente armazenado 10000 = 16, expoente real = 16 − 15 = 1. Mantissa 100000 = 0,5 em fração, dando significando 1,5 (bit implícito 1). Valor = 1,5 × 2¹ = 3,0.'),
  reviewMC({id:'rev_p1_float_encode_neg',category:'ieee754_custom',subtopic:'conversão para binário',errorType:'ponto flutuante',quickRule:'Normalize a 1,xxx × 2^e antes de montar os campos.'},
    'Qual é a representação em binário (1 sinal + 5 expoente + 6 mantissa, bias 15) do número <b>−8,0</b>?',
    ['1 10010 000000','0 10010 000000','1 01101 000000','1 10011 000000'],0,
    '−8 é negativo: sinal=1. 8 = 1,0 × 2³, expoente real=3, armazenado = 3+15=18 = 10010. A mantissa (parte fracionária após o 1 implícito) é 000000.'),
  reviewTF({id:'rev_p1_float_implicit_bit',category:'ieee754_custom',subtopic:'bit implícito',errorType:'ponto flutuante',quickRule:'O 1 antes da vírgula não é armazenado.'},
    'Nesse formato de ponto flutuante, o bit mais à esquerda da mantissa (o "1" antes da vírgula) é armazenado explicitamente nos bits do número.',
    false,
    'Falso. Como todo número normalizado começa com 1,xxx, esse bit é implícito — só a parte fracionária (mantissa) ocupa espaço nos bits armazenados.'),
  reviewMC({id:'rev_p1_float_range_precision_tradeoff',category:'ieee754_custom',subtopic:'faixa vs precisão',errorType:'ponto flutuante',quickRule:'Expoente = faixa; mantissa = precisão.'},
    'Em um formato de ponto flutuante de tamanho fixo, se aumentarmos o número de bits do expoente e diminuirmos o da mantissa (mantendo o total), o que acontece?',
    ['Aumenta a faixa (range) de valores representáveis, mas diminui a precisão','Aumenta a precisão, mas diminui a faixa de valores','Não há nenhuma mudança, pois o total de bits é o mesmo','Aumenta tanto a faixa quanto a precisão'],0,
    'Mais bits de expoente permitem representar números muito maiores ou menores (mais faixa), mas sobram menos bits para a mantissa, reduzindo a precisão (quantidade de dígitos significativos).'),
  reviewMC({id:'rev_p1_float_sum_decimal',category:'ieee754_custom',subtopic:'soma decimal',errorType:'ponto flutuante',quickRule:'Some os valores decimais já convertidos.'},
    'Some os dois números <span class="mono">0 01111 000000</span> (que vale 1,0) e <span class="mono">0 10000 100000</span> (que vale 3,0) nesse formato de ponto flutuante e indique o valor decimal do resultado.',
    ['4,0','3,5','2,0','4,5'],0,
    'O primeiro número vale 1,0 e o segundo vale 3,0. A soma é 1,0 + 3,0 = 4,0.'),
  reviewAR({id:'rev_p1_float_overflow_exponent',category:'ieee754_custom',subtopic:'overflow',errorType:'ponto flutuante',quickRule:'Overflow depende do expoente, não da mantissa.'},
    '"Overflow em ponto flutuante ocorre quando o expoente calculado é grande demais para caber nos bits reservados para o expoente, e não está relacionado à quantidade de bits da mantissa."',
    true,
    'Verdadeiro. Overflow (e underflow) em ponto flutuante dependem da faixa do expoente. A mantissa afeta apenas a precisão, não a faixa de valores representáveis.'),
  reviewTF({id:'rev_p1_float_same_bits_diff_format',category:'ieee754_custom',subtopic:'formatos diferentes',errorType:'ponto flutuante',quickRule:'A divisão expoente/mantissa muda o conjunto de números representáveis.'},
    'Dois formatos de ponto flutuante com a mesma quantidade total de bits sempre representam exatamente os mesmos números.',
    false,
    'Falso. A divisão de bits entre expoente e mantissa muda a faixa e a precisão representáveis; dois formatos com o mesmo total de bits mas larguras diferentes de expoente/mantissa representam conjuntos de números diferentes.')
];

const AMDAHL_SPEEDUP_REVIEW = [
  reviewMC({id:'rev_p1_amdahl_basic_speedup',category:'amdahl_speedup',subtopic:'speedup básico',errorType:'Amdahl',quickRule:'speedup = tempo antigo / tempo novo.'},
    'Uma máquina A executa um programa em 8 s e uma máquina B executa o mesmo programa em 20 s. Quantas vezes A é mais rápida que B?',
    ['2,5','0,4','12','28'],0,
    'Speedup = tempo de B / tempo de A = 20/8 = 2,5. A é 2,5 vezes mais rápida que B.'),
  reviewMC({id:'rev_p1_amdahl_formula_basic',category:'amdahl_speedup',subtopic:'fórmula de Amdahl',errorType:'Amdahl',quickRule:'Sup_total = 1 / ((1−Fm) + Fm/SupFm).'},
    'Uma parte de um programa corresponde a 40% (Fm=0,4) do tempo de execução e será acelerada 5 vezes (SupFm=5). Qual o speedup total, pela Lei de Amdahl?',
    ['≈1,47','≈2,00','≈5,00','≈0,68'],0,
    'Sup_total = 1/((1−Fm)+Fm/SupFm) = 1/(0,6+0,4/5) = 1/(0,6+0,08) = 1/0,68 ≈ 1,47.'),
  reviewMC({id:'rev_p1_amdahl_coprocessor',category:'amdahl_speedup',subtopic:'coprocessador',errorType:'Amdahl',quickRule:'Aplique a fórmula com o Fm e o SupFm do enunciado.'},
    'Um coprocessador torna certas operações 4 vezes mais rápidas. Essas operações correspondem a 25% do tempo de execução (Fm=0,25) e o coprocessador é usado sempre que possível. Qual o speedup total?',
    ['≈1,23','≈1,33','≈4,00','≈0,81'],0,
    'Sup_total = 1/((1−0,25)+0,25/4) = 1/(0,75+0,0625) = 1/0,8125 ≈ 1,23.'),
  reviewTF({id:'rev_p1_amdahl_limit_suptotal',category:'amdahl_speedup',subtopic:'limite do speedup',errorType:'Amdahl',quickRule:'Sup_total nunca ultrapassa SupFm.'},
    'Pela Lei de Amdahl, o speedup total pode ultrapassar o speedup da parte melhorada isoladamente (SupFm), mesmo que essa parte seja usada o tempo todo (Fm=1).',
    false,
    'Falso. O speedup total nunca ultrapassa SupFm; o máximo teórico (Fm=1, toda a execução usa a melhoria) faz Sup_total = SupFm. Com Fm<1 na prática, o speedup total fica sempre abaixo disso — essa é a essência da Lei de Amdahl: a parte não melhorada limita o ganho.'),
  reviewTF({id:'rev_p1_amdahl_fm_zero',category:'amdahl_speedup',subtopic:'Fm=0',errorType:'Amdahl',quickRule:'Fm=0 → Sup_total=1, sempre.'},
    'Se Fm=0 (a melhoria não é usada em nenhuma parte do tempo de execução), o speedup total é sempre 1, independente do valor de SupFm.',
    true,
    'Verdadeiro. Sem nenhuma fração do tempo usando a melhoria (Fm=0), o desempenho não muda: Sup_total = 1/(1+0) = 1.'),
  reviewMC({id:'rev_p1_amdahl_solve_fm',category:'amdahl_speedup',subtopic:'resolver para Fm',errorType:'Amdahl',quickRule:'Isole Fm na fórmula de Amdahl a partir do speedup desejado.'},
    'Queremos um speedup total de 2 vezes melhorando uma parte do sistema em 10 vezes (SupFm=10). Qual fração do tempo (Fm) essa parte melhorada precisa representar?',
    ['≈55,6%','≈50,0%','≈20,0%','≈90,0%'],0,
    '2 = 1/((1−Fm)+Fm/10) → (1−Fm)+0,1·Fm = 0,5 → 1 − 0,9·Fm = 0,5 → Fm = 0,5/0,9 ≈ 0,556, ou seja, ≈55,6%.'),
  reviewMC({id:'rev_p1_amdahl_common_case',category:'amdahl_speedup',subtopic:'caso comum',errorType:'Amdahl',quickRule:'Otimize o que acontece com mais frequência.'},
    'Segundo o princípio do caso comum, ao otimizar o desempenho de um processador devemos priorizar:',
    ['O caso mais frequente de uso, mesmo que otimizar casos raros seja tecnicamente mais fácil','Sempre o caso mais raro, pois ele geralmente é o mais lento','Todos os casos igualmente, sem priorização','Apenas casos que envolvem overflow'],0,
    'O princípio do caso comum (common case) diz que vale mais a pena otimizar o que acontece com mais frequência: mesmo um pequeno ganho num caso muito frequente costuma superar um grande ganho num caso raro.'),
  reviewAR({id:'rev_p1_amdahl_speedup_equivalence',category:'amdahl_speedup',subtopic:'definições equivalentes',errorType:'Amdahl',quickRule:'Performance = 1/tempo, então as duas razões coincidem.'},
    '"Duas definições equivalentes de speedup são: a razão entre as performances (Performance nova / Performance antiga) e a razão inversa entre os tempos de execução (Tempo antigo / Tempo novo)."',
    true,
    'Verdadeiro. Como performance = 1/tempo, Performance_nova/Performance_antiga = Tempo_antigo/Tempo_novo — as duas formas são equivalentes.')
];

const CPI_DESEMPENHO_P1_REVIEW = [
  reviewMC({id:'rev_p1_cpi_avg_table',category:'cpi_desempenho_p1',subtopic:'CPI médio',errorType:'CPI médio',quickRule:'CPI médio = soma(fração_i × CPI_i).'},
    'Máquina X roda a 400 MHz. Tabela de instruções: ULA 50% (CPI 4) · Desvios 15% (CPI 3) · Memória 30% (CPI 6) · Outras 5% (CPI 8). Qual o CPI médio dessa máquina?',
    ['4,65','4,00','5,00','3,80'],0,
    'CPI médio = 0,50×4 + 0,15×3 + 0,30×6 + 0,05×8 = 2 + 0,45 + 1,8 + 0,4 = 4,65.'),
  reviewMC({id:'rev_p1_cpi_cycle_time',category:'cpi_desempenho_p1',subtopic:'tempo de ciclo',errorType:'CPI médio',quickRule:'Tempo de ciclo = 1/frequência.'},
    'Qual o tempo de ciclo de clock de uma máquina que opera a 400 MHz?',
    ['2,5 ns','4,0 ns','0,4 ns','25 ns'],0,
    'Tempo de ciclo = 1/frequência = 1/(400×10⁶) = 2,5 ns.'),
  reviewMC({id:'rev_p1_cpi_total_time',category:'cpi_desempenho_p1',subtopic:'tempo total',errorType:'CPI médio',quickRule:'Tempo total = instruções × CPI médio × tempo de ciclo.'},
    'Uma máquina com clock de 400 MHz e CPI médio de 4,65 executa um programa de 10.000 instruções. Qual o tempo total de execução?',
    ['116,25 µs','46,50 µs','25,00 µs','186,00 µs'],0,
    'Tempo de ciclo = 2,5 ns. Tempo total = 10.000 × 4,65 × 2,5 ns = 116.250 ns = 116,25 µs.'),
  reviewMC({id:'rev_p1_cpi_mips_rate',category:'cpi_desempenho_p1',subtopic:'taxa MIPS',errorType:'CPI médio',quickRule:'MIPS = frequência / (CPI médio × 10⁶).'},
    'Qual a taxa de MIPS (milhões de instruções por segundo) de uma máquina com clock de 400 MHz e CPI médio de 4,65?',
    ['≈86,0','≈400,0','≈4,65','≈21,5'],0,
    'MIPS = frequência(Hz) / (CPI médio × 10⁶) = 400×10⁶ / (4,65×10⁶) ≈ 86,0.'),
  reviewTF({id:'rev_p1_cpi_weighted_avg_tf',category:'cpi_desempenho_p1',subtopic:'média ponderada',errorType:'CPI médio',quickRule:'CPI médio é ponderado pela fração de uso, não uma média simples.'},
    'O CPI médio é calculado somando os CPIs de cada tipo de instrução e dividindo pela quantidade de tipos diferentes, sem considerar a frequência de uso de cada um.',
    false,
    'Falso. O CPI médio é uma média ponderada pela fração (%) de uso de cada tipo: CPI médio = Σ(fração_i × CPI_i), não uma média simples entre os CPIs.'),
  reviewMC({id:'rev_p1_cpi_speedup_compiler',category:'cpi_desempenho_p1',subtopic:'speedup por CPI',errorType:'CPI médio',quickRule:'Com mesma frequência e instruções, speedup = CPI antigo / CPI novo.'},
    'Se um novo compilador reduzir o CPI médio de uma máquina de 4,65 para 3,00 (mantendo a mesma frequência e a mesma quantidade de instruções), qual o speedup obtido?',
    ['≈1,55','≈0,65','≈3,00','≈4,65'],0,
    'Com a mesma frequência e mesma quantidade de instruções, o tempo é proporcional ao CPI. Speedup = CPI_antigo / CPI_novo = 4,65 / 3,00 ≈ 1,55.'),
  reviewAR({id:'rev_p1_cpi_mips_isa_caveat',category:'cpi_desempenho_p1',subtopic:'MIPS e ISA',errorType:'CPI médio',quickRule:'MIPS só compara máquinas com o mesmo conjunto de instruções.'},
    '"Para comparar duas máquinas usando MIPS, é necessário que ambas executem o mesmo conjunto de instruções (mesmo programa), pois máquinas com conjuntos de instruções diferentes podem precisar de quantidades de instruções muito diferentes para a mesma tarefa."',
    true,
    'Verdadeiro. MIPS é sensível ao conjunto de instruções: uma máquina pode ter MIPS alto usando instruções simples demais, precisando de mais instruções para a mesma tarefa — por isso comparar MIPS entre ISAs diferentes pode enganar.'),
  reviewTF({id:'rev_p1_cpi_reduce_time_tf',category:'cpi_desempenho_p1',subtopic:'reduzir CPI',errorType:'CPI médio',quickRule:'Tempo = instruções × CPI × tempo de ciclo.'},
    'Reduzir o CPI médio de uma máquina, mantendo a frequência do clock e a quantidade de instruções executadas, sempre reduz o tempo total de execução.',
    true,
    'Verdadeiro. Tempo de execução = nº instruções × CPI médio × tempo de ciclo. Se instruções e tempo de ciclo não mudam, reduzir o CPI médio reduz diretamente o tempo total.')
];

// Questoes abertas removidas: a Prova 1 real e 100% de multipla escolha
// (ver materiais-privados/Prova1), entao o banco de pratica nao inclui
// formato aberto — mantem paridade com o formato real da prova.
const P1_OPEN_QUESTIONS = [];
