/* ===========================================================================
   CONTEUDO — prova2.js
   Banco de questoes da Prova 2: enderecamento de vetores, deslocamento
   (sll/srl/sra), CPI medio/desempenho a partir de um programa, pilha em
   chamadas de funcao, e questoes abertas. Carrega depois de
   content/factories.js.
   =========================================================================== */

const ENDERECAMENTO_VETOR_REVIEW = [
  reviewMC({id:'rev_p2_addr_index_offset',category:'enderecamento_vetor',subtopic:'offset por índice',errorType:'endereçamento',quickRule:'Deslocamento em bytes = índice × tamanho do elemento.'},
    'O endereço-base de um vetor de inteiros (4 bytes cada) está em $s2. Qual instrução carrega o elemento <span class="mono">vet[7]</span> em $t0?',
    ['lw $t0, 28($s2)','lw $t0, 7($s2)','lw $t0, 32($s2)','lw $s2, 28($t0)'],0,
    'Cada inteiro ocupa 4 bytes, então vet[7] está a 7×4=28 bytes da base. A instrução correta é lw $t0, 28($s2).'),
  reviewMC({id:'rev_p2_addr_last_element',category:'enderecamento_vetor',subtopic:'último elemento',errorType:'endereçamento',quickRule:'Com N elementos, o último tem índice N-1.'},
    'O registrador $s3 contém o endereço inicial de um vetor de 12 inteiros consecutivos (4 bytes cada). Qual instrução carrega o último elemento em $t1?',
    ['lw $t1, 44($s3)','lw $t1, 48($s3)','lw $t1, 12($s3)','lw $t1, 11($s3)'],0,
    'Com 12 elementos indexados de 0 a 11, o último tem índice 11: deslocamento = 11×4=44 bytes.'),
  reviewMC({id:'rev_p2_addr_store_element',category:'enderecamento_vetor',subtopic:'sw em vetor',errorType:'endereçamento',quickRule:'Gravar usa sw; o offset continua índice×4.'},
    'O registrador $t2 guarda um valor que deve ser salvo na posição <span class="mono">vet[5]</span> de um vetor cujo endereço-base está em $s0 (inteiros de 4 bytes). Qual instrução faz isso?',
    ['sw $t2, 20($s0)','lw $t2, 20($s0)','sw $s0, 20($t2)','sw $t2, 5($s0)'],0,
    'Para gravar usa-se sw. O deslocamento continua sendo índice×4 = 5×4=20 bytes: sw $t2, 20($s0).'),
  reviewMC({id:'rev_p2_addr_build_const_shift',category:'enderecamento_vetor',subtopic:'constante via shift',errorType:'endereçamento',quickRule:'sll desloca à esquerda = multiplica por 2^shamt.'},
    'O registrador $s0 contém o valor 1. Qual instrução resulta em $s0 = 0x10000000 (um "1" seguido de 28 bits zero)?',
    ['sll $s0, $s0, 28','sll $s0, $s0, 4','sll $s0, $s0, 16','srl $s0, $s0, 28'],0,
    '0x10000000 = 2²⁸. Deslocar 1 à esquerda 28 vezes (sll $s0,$s0,28) multiplica por 2²⁸, produzindo exatamente esse valor.'),
  reviewMC({id:'rev_p2_addr_dynamic_index',category:'enderecamento_vetor',subtopic:'índice em registrador',errorType:'endereçamento',quickRule:'Índice em registrador → sll por 2 (×4) e some à base.'},
    'O índice de um elemento está guardado em $t0 (não é uma constante fixa), e o endereço-base do vetor (inteiros de 4 bytes) está em $s1. Qual sequência calcula o endereço do elemento e carrega seu valor em $t2?',
    ['sll $t1, $t0, 2<br>add $t1, $t1, $s1<br>lw $t2, 0($t1)','add $t1, $t0, $s1<br>lw $t2, 0($t1)','sll $t1, $t0, 4<br>add $t1, $t1, $s1<br>lw $t2, 0($t1)','lw $t2, 0($t0)'],0,
    'Como o índice está em um registrador, não dá para usar índice×4 como imediato. sll $t1,$t0,2 multiplica o índice por 4 (tamanho do inteiro), soma-se à base com add, e só então usa-se lw com deslocamento 0.'),
  reviewTF({id:'rev_p2_addr_offset_formula_tf',category:'enderecamento_vetor',subtopic:'fórmula do offset',errorType:'endereçamento',quickRule:'A fórmula índice×tamanho vale tanto pra constante quanto pra registrador.'},
    'Ao acessar vet[i] em um vetor de inteiros (4 bytes cada), o deslocamento em bytes a partir da base é sempre i×4, mesmo quando i está guardado em um registrador em tempo de execução.',
    true,
    'Verdadeiro. A fórmula do deslocamento (índice × tamanho do elemento) não muda; o que muda é como ela é calculada: constante vira imediato direto, e registrador exige sll (ou multiplicação) mais soma em tempo de execução.'),
  reviewMC({id:'rev_p2_addr_reverse_index',category:'enderecamento_vetor',subtopic:'índice a partir do endereço',errorType:'endereçamento',quickRule:'índice = diferença de endereços ÷ tamanho do elemento.'},
    'O endereço-base de um vetor de inteiros está em $s0. Um ponteiro em $t0 aponta para um elemento do vetor, e $t0 − $s0 = 36 (em bytes). Qual é o índice desse elemento?',
    ['9','36','4','144'],0,
    'O índice é a diferença de endereços dividida pelo tamanho do elemento: 36 ÷ 4 = 9.'),
  reviewAR({id:'rev_p2_addr_byte_array_ar',category:'enderecamento_vetor',subtopic:'vetor de bytes',errorType:'endereçamento',quickRule:'Vetor de 1 byte por elemento: offset = índice, sem multiplicar.'},
    '"Para um vetor de bytes (char, 1 byte cada), o deslocamento em memória para acessar o elemento de índice i é igual a i, sem precisar multiplicar por nenhum tamanho de elemento."',
    true,
    'Verdadeiro. Como cada elemento ocupa exatamente 1 byte, o deslocamento em bytes é igual ao próprio índice — diferente de vetores de inteiros (4 bytes), que exigem multiplicar o índice por 4.')
];

const DESLOCAMENTO_SHIFT_REVIEW = [
  reviewMC({id:'rev_p2_shift_divide_1024',category:'deslocamento_shift',subtopic:'divisão com sinal',errorType:'shift',quickRule:'Dividir por 2^n com sinal: sra por n.'},
    'Qual instrução divide (parte inteira) o valor com sinal de um registrador por 1024, preservando corretamente o sinal do resultado?',
    ['sra $s0, $s1, 10','srl $s0, $s1, 10','sll $s0, $s1, 10','sra $s0, $s1, 1024'],0,
    'Dividir por 1024=2¹⁰ corresponde a deslocar 10 bits à direita. Para números com sinal, usa-se sra (shift right arithmetic), que preserva o bit de sinal.'),
  reviewMC({id:'rev_p2_shift_multiply_32',category:'deslocamento_shift',subtopic:'multiplicação',errorType:'shift',quickRule:'Multiplicar por 2^n: sll por n.'},
    'Qual instrução multiplica o valor de $t0 por 32 e guarda o resultado em $t1?',
    ['sll $t1, $t0, 5','sll $t1, $t0, 32','srl $t1, $t0, 5','sra $t1, $t0, 5'],0,
    'Multiplicar por 32=2⁵ equivale a deslocar 5 bits à esquerda: sll $t1,$t0,5.'),
  reviewTF({id:'rev_p2_shift_srl_zero_fill_tf',category:'deslocamento_shift',subtopic:'srl',errorType:'shift',quickRule:'srl sempre preenche com zero.'},
    'srl (shift right logical) preenche os bits mais à esquerda com zero, independente do sinal do número original.',
    true,
    'Verdadeiro. srl sempre preenche com zeros, por isso não deve ser usado para dividir números negativos (nesse caso o correto é sra, que replica o bit de sinal).'),
  reviewTF({id:'rev_p2_shift_sra_sign_tf',category:'deslocamento_shift',subtopic:'sra',errorType:'shift',quickRule:'sra replica o bit de sinal.'},
    'sra (shift right arithmetic) preenche os bits mais à esquerda repetindo o bit de sinal original, preservando corretamente a divisão de números negativos por potências de 2.',
    true,
    'Verdadeiro. sra copia o bit de sinal nos bits que entram pela esquerda, o que corresponde à divisão inteira correta de números negativos.'),
  reviewMC({id:'rev_p2_shift_sra_example',category:'deslocamento_shift',subtopic:'exemplo numérico',errorType:'shift',quickRule:'sra por n divide por 2^n preservando sinal.'},
    '$s1 contém o valor −16. Qual o resultado de <span class="mono">sra $s0, $s1, 2</span>?',
    ['-4','4','-64','-8'],0,
    'sra desloca 2 bits à direita preservando o sinal, equivalente a dividir por 4 (2²): −16 ÷ 4 = −4.'),
  reviewMC({id:'rev_p2_shift_srl_misuse',category:'deslocamento_shift',subtopic:'uso incorreto de srl',errorType:'shift',quickRule:'srl em número negativo destrói o sinal.'},
    '$s1 contém o valor −8 (complemento de dois, 32 bits). O que acontece se usarmos <span class="mono">srl $s0, $s1, 1</span> em vez de sra?',
    ['O resultado vira um número positivo muito grande, porque o bit de sinal é substituído por zero','O resultado é -4, igual ao sra','O resultado é 0','O programa trava (exceção de hardware)'],0,
    'srl sempre insere zero pela esquerda. Em um número negativo (bit de sinal 1), isso destrói o sinal: o valor deixa de representar −4 e passa a ser um número positivo enorme.'),
  reviewMC({id:'rev_p2_shift_build_mask',category:'deslocamento_shift',subtopic:'montar constante',errorType:'shift',quickRule:'Cada dígito hexadecimal desocupado à direita = 4 bits de shift.'},
    'Qual instrução coloca o valor 0xFF00 em $s0, partindo de $s0 = 0xFF?',
    ['sll $s0, $s0, 8','sll $s0, $s0, 16','srl $s0, $s0, 8','sra $s0, $s0, 8'],0,
    '0xFF00 = 0xFF deslocado 8 bits (2 dígitos hexadecimais = 8 bits) à esquerda: sll $s0,$s0,8.'),
  reviewAR({id:'rev_p2_shift_sll_both_signs_ar',category:'deslocamento_shift',subtopic:'sll e sinal',errorType:'shift',quickRule:'sll não distingue sinal; por isso só existe uma versão dele.'},
    '"sll (shift left logical) sempre preenche os bits que entram pela direita com zero, e isso vale tanto para deslocar números positivos quanto negativos."',
    true,
    'Verdadeiro. sll sempre insere zeros pela direita, independente do sinal — por isso só existe uma versão de shift left, mas duas de shift right (lógica e aritmética).')
];

const CPI_DESEMPENHO_P2_REVIEW = [
  reviewMC({id:'rev_p2_cpi_program_total_instr',category:'cpi_desempenho_p2',subtopic:'contagem dinâmica',errorType:'CPI médio',quickRule:'Conte instruções fora do loop + (instruções do loop × repetições).'},
    'Considere o programa MIPS abaixo, sabendo que o loop (linhas 3 a 7) executa exatamente 5 vezes antes de sair:<pre class="program-code">1  ori  $s0, $zero, 5     ; ULA\n2  addi $s1, $zero, 0     ; ULA\n3  loop: lw $t0, 0($s2)   ; Memória\n4  add  $s1, $s1, $t0     ; ULA\n5  addi $s2, $s2, 4       ; ULA\n6  addi $s0, $s0, -1      ; ULA\n7  bne  $s0, $zero, loop  ; Desvio\n8  sw   $s1, 0($s3)       ; Memória</pre>Quantas instruções são executadas dinamicamente ao todo?',
    ['28','25','30','8'],0,
    'Linhas 1, 2 e 8 executam 1 vez cada (3). As linhas 3 a 7 (5 instruções) executam 5 vezes cada (25). Total = 3 + 25 = 28.'),
  reviewMC({id:'rev_p2_cpi_program_ula_count',category:'cpi_desempenho_p2',subtopic:'contagem por tipo',errorType:'CPI médio',quickRule:'Classifique cada linha e multiplique pelas repetições do loop.'},
    'No mesmo programa, sabendo que o loop (linhas 3 a 7) executa exatamente 5 vezes:<pre class="program-code">1  ori  $s0, $zero, 5     ; ULA\n2  addi $s1, $zero, 0     ; ULA\n3  loop: lw $t0, 0($s2)   ; Memória\n4  add  $s1, $s1, $t0     ; ULA\n5  addi $s2, $s2, 4       ; ULA\n6  addi $s0, $s0, -1      ; ULA\n7  bne  $s0, $zero, loop  ; Desvio\n8  sw   $s1, 0($s3)       ; Memória</pre>Quantas dessas instruções executadas são do tipo ULA?',
    ['17','15','20','12'],0,
    '2 instruções de ULA fora do loop (linhas 1 e 2) + 3 instruções de ULA dentro do loop (linhas 4, 5 e 6) × 5 repetições = 2 + 15 = 17.'),
  reviewMC({id:'rev_p2_cpi_avg_given_counts',category:'cpi_desempenho_p2',subtopic:'CPI médio',errorType:'CPI médio',quickRule:'CPI médio = ciclos totais / instruções totais.'},
    'Um programa executa dinamicamente 17 instruções de ULA (CPI=4), 5 desvios (CPI=3) e 6 acessos à memória (CPI=5). Qual o CPI médio desse programa?',
    ['≈4,04','≈4,00','≈3,50','≈5,00'],0,
    'Ciclos totais = 17×4 + 5×3 + 6×5 = 68+15+30 = 113. Total de instruções = 17+5+6 = 28. CPI médio = 113/28 ≈ 4,04.'),
  reviewMC({id:'rev_p2_cpi_total_time_given_cycles',category:'cpi_desempenho_p2',subtopic:'tempo total',errorType:'CPI médio',quickRule:'Tempo total = ciclos totais × tempo de ciclo.'},
    'Uma máquina com clock de 250 MHz executa um programa cujo total de ciclos gastos é 113. Qual o tempo total de execução?',
    ['452 ns','448 ns','500 ns','113 ns'],0,
    'Tempo de ciclo = 1/250MHz = 4 ns. Tempo total = 113 × 4 ns = 452 ns.'),
  reviewTF({id:'rev_p2_cpi_dynamic_loop_tf',category:'cpi_desempenho_p2',subtopic:'contagem dinâmica',errorType:'CPI médio',quickRule:'Contagem dinâmica conta execuções reais, não linhas de código.'},
    'Instruções dentro de um loop que se repete N vezes devem ser contadas N vezes na contagem dinâmica de instruções, mesmo aparecendo apenas uma vez no código-fonte.',
    true,
    'Verdadeiro. Contagem dinâmica reflete a execução real: uma instrução dentro de um loop de N repetições é executada N vezes, mesmo escrita uma única vez no programa.'),
  reviewMC({id:'rev_p2_cpi_loop_control_instr',category:'cpi_desempenho_p2',subtopic:'controle do loop',errorType:'CPI médio',quickRule:'Quem decide o fluxo é o desvio condicional, não o decremento.'},
    'Em um loop controlado por uma instrução <span class="mono">addi $s0, $s0, -1</span> seguida de <span class="mono">bne $s0, $zero, loop</span>, qual instrução decide se o loop deve continuar ou terminar?',
    ['bne $s0, $zero, loop','addi $s0, $s0, -1','Nenhuma das duas: isso depende do compilador','As duas decidem igualmente'],0,
    'O bne é o desvio condicional: compara $s0 com zero e decide se volta para "loop". O addi só atualiza o contador; quem decide o fluxo é o bne.'),
  reviewAR({id:'rev_p2_cpi_loop_change_ar',category:'cpi_desempenho_p2',subtopic:'mudar o passo do loop',errorType:'CPI médio',quickRule:'Mudar quantas vezes o loop repete muda a contagem dinâmica total.'},
    '"Se alterarmos a instrução de decremento de um loop para decrementar de 2 em 2 em vez de 1 em 1, a quantidade de vezes que o loop executa (e portanto a contagem dinâmica total de instruções) pode mudar."',
    true,
    'Verdadeiro. Decrementar mais rápido normalmente faz o contador chegar à condição de parada mais cedo, reduzindo quantas vezes as instruções do corpo do loop são contadas dinamicamente.'),
  reviewMC({id:'rev_p2_cpi_mips_rate',category:'cpi_desempenho_p2',subtopic:'taxa MIPS',errorType:'CPI médio',quickRule:'MIPS = frequência / (CPI médio × 10⁶).'},
    'Qual a taxa de MIPS de uma máquina com clock de 250 MHz e CPI médio de 4,04?',
    ['≈61,9','≈250,0','≈4,04','≈100,0'],0,
    'MIPS = frequência / (CPI médio × 10⁶) = 250×10⁶ / (4,04×10⁶) ≈ 61,9.')
];

const PILHA_FUNCOES_P2_REVIEW = [
  reviewMC({id:'rev_p2_stack_one_level',category:'pilha_funcoes_p2',subtopic:'uso mínimo da pilha',errorType:'pilha',quickRule:'Só quem chama outra função depois de ser chamada precisa salvar $ra.'},
    'main() chama funcaoA(); funcaoA() chama funcaoB(); funcaoB() não chama nenhuma outra função. Usando a estratégia de uso mínimo da pilha, quantas vezes o registrador $ra precisa ser salvo na pilha ao todo?',
    ['1','0','2','3'],0,
    'Só quem chama outra função depois de já ter sido chamado precisa preservar seu próprio $ra. funcaoA é chamada por main e chama funcaoB — precisa salvar seu $ra antes do jal para funcaoB. funcaoB é folha e não precisa salvar nada.'),
  reviewMC({id:'rev_p2_stack_two_levels',category:'pilha_funcoes_p2',subtopic:'uso mínimo da pilha',errorType:'pilha',quickRule:'Conte um salvamento por função não-folha na cadeia.'},
    'main() chama A(); A() chama B(); B() chama C(); C() não chama ninguém. Quantas vezes $ra precisa ser salvo na pilha, no uso mínimo?',
    ['2','1','3','0'],0,
    'A e B chamam outra função depois de terem sido chamadas, então cada uma salva seu próprio $ra uma vez (2 salvamentos). C é folha e não precisa salvar.'),
  reviewTF({id:'rev_p2_stack_leaf_never_tf',category:'pilha_funcoes_p2',subtopic:'função-folha',errorType:'pilha',quickRule:'Função-folha nunca executa jal, então nunca sobrescreve seu $ra.'},
    'Uma função que não chama nenhuma outra função (função-folha) nunca precisa salvar $ra na pilha, mesmo sendo chamada por outra função.',
    true,
    'Verdadeiro. $ra só é sobrescrito quando a própria função executa um jal para chamar outra função. Uma função-folha nunca faz isso, então seu $ra permanece intacto até o jr $ra de retorno.'),
  reviewTF({id:'rev_p2_stack_sequential_calls_tf',category:'pilha_funcoes_p2',subtopic:'chamadas sequenciais',errorType:'pilha',quickRule:'Chamadas sequenciais (não aninhadas) reaproveitam um único salvamento.'},
    'Se uma função chama outra função duas vezes em sequência (não aninhadas), ela precisa salvar $ra duas vezes, uma para cada chamada.',
    false,
    'Falso. Entre chamadas sequenciais (não aninhadas), $ra pode ser salvo uma única vez antes da primeira chamada e restaurado só ao final, contanto que nenhuma chamada aninhada sobrescreva esse valor salvo entre elas.'),
  reviewMC({id:'rev_p2_stack_save_sequence',category:'pilha_funcoes_p2',subtopic:'sequência de salvamento',errorType:'pilha',quickRule:'Primeiro reserva espaço (decrementa $sp), depois grava.'},
    'Para salvar $ra na pilha em MIPS, qual sequência de instruções está correta?',
    ['addi $sp, $sp, -4<br>sw $ra, 0($sp)','sw $ra, 0($sp)<br>addi $sp, $sp, -4','addi $sp, $sp, 4<br>sw $ra, 0($sp)','lw $ra, 0($sp)<br>addi $sp, $sp, -4'],0,
    'Primeiro reserva-se espaço decrementando $sp (a pilha cresce para endereços menores), depois grava-se o valor com sw. Fazer sw antes de mover $sp arrisca sobrescrever dados de outra função.'),
  reviewMC({id:'rev_p2_stack_restore_sequence',category:'pilha_funcoes_p2',subtopic:'sequência de restauração',errorType:'pilha',quickRule:'Primeiro lê o valor salvo, depois libera o espaço (incrementa $sp).'},
    'Qual sequência restaura corretamente $ra da pilha antes de retornar com jr $ra?',
    ['lw $ra, 0($sp)<br>addi $sp, $sp, 4','addi $sp, $sp, 4<br>lw $ra, 0($sp)','sw $ra, 0($sp)<br>addi $sp, $sp, 4','addi $sp, $sp, -4<br>lw $ra, 0($sp)'],0,
    'Primeiro lê-se o valor salvo com lw (enquanto $sp ainda aponta para ele), depois libera-se o espaço incrementando $sp. Inverter a ordem leria um endereço já considerado livre.'),
  reviewAR({id:'rev_p2_stack_sp_grows_down_ar',category:'pilha_funcoes_p2',subtopic:'$sp cresce para baixo',errorType:'pilha',quickRule:'Reservar espaço = diminuir $sp; liberar = aumentar $sp.'},
    '"O ponteiro de pilha ($sp) deve apontar sempre para o topo da pilha, e reservar espaço na pilha significa diminuir o valor de $sp, pois a pilha em MIPS cresce em direção a endereços menores."',
    true,
    'Verdadeiro. Por convenção MIPS, a pilha cresce para baixo (endereços decrescentes): reservar espaço é subtrair de $sp, e liberar espaço é somar a $sp.'),
  reviewMC({id:'rev_p2_stack_sequential_two_calls',category:'pilha_funcoes_p2',subtopic:'chamadas sequenciais',errorType:'pilha',quickRule:'Chamadas sequenciais da mesma função reaproveitam um único salvamento.'},
    'main() chama f1(); f1() chama f2() duas vezes, em sequência (não aninhadas); nenhuma chamada de f2() faz outra chamada. Quantas vezes $ra precisa ser salvo na pilha, no uso mínimo?',
    ['1','2','0','3'],0,
    'f1 chama f2 duas vezes, mas não são chamadas aninhadas — um único salvamento de $ra antes da primeira chamada é suficiente, pois o valor salvo continua protegido na pilha durante toda a sequência.')
];

// Questoes abertas removidas: a Prova 2 real e 100% de multipla escolha,
// entao o banco de pratica nao inclui formato aberto.
const P2_OPEN_QUESTIONS = [];
