import type { Topic } from '../types';

export const buscaTopics: Topic[] = [
  {
    id: 'bfs',
    moduleId: 'busca-alcancabilidade',
    order: 1,
    slug: 'bfs',
    title: 'Busca em largura (BFS)',
    examLikelihood: 'high',
    examEvidence: '2023/1-Q5 (25%, maior peso da prova) pede projeto de algoritmo de BFS para contar arestas até todos os vértices.',
    whatYouNeedToKnow:
      'BFS explora o grafo "em camadas" a partir de um vértice s, usando uma fila (FIFO). Distância(s)=0; ao visitar v, todo vizinho não visitado recebe Distância(v)+1 e entra na fila. A ordem de saída da fila é não-decrescente em distância — por isso BFS encontra o caminho mais curto em número de arestas (grafo não-ponderado).',
    understand: [
      'Pseudocódigo do professor (ver Resumo Prova 1): inicializa distâncias em −1 (não visitado); Distância(s)=0; fila={s}; enquanto fila não vazia: remove início da fila, para cada vizinho não visitado adiciona ao fim da fila e Distância(vizinho)=Distância(atual)+1.',
      'A ordem de desenfileiramento é a ordem de "descoberta por nível" — todos os vértices a distância 1 saem antes dos de distância 2.',
      'Se a questão pedir "prioridade alfabética", ao enfileirar os vizinhos de um vértice, insira-os em ordem alfabética.',
      'Aplicação direta: BFS a partir de v conta, para cada outro vértice, o menor número de arestas até ele — é assim que se calcula excentricidade em grafo não-ponderado.',
    ],
    commonPitfall: 'Confundir fila (BFS, FIFO) com pilha (DFS, LIFO) — usar a estrutura errada muda completamente a ordem de visita.',
    sources: [{ type: 'professor_support_material', file: 'Resumo Prova 1 Grafos.pdf' }, { type: 'professor_support_material', file: 'Flash Cards Grafos-1.pdf' }],
  },
  {
    id: 'dfs-classificacao',
    moduleId: 'busca-alcancabilidade',
    order: 2,
    slug: 'dfs-classificacao',
    title: 'Busca em profundidade (DFS) e classificação de arestas',
    examLikelihood: 'high',
    examEvidence: '2022/2-Q3 pede simulação de DFS com prioridade alfabética + detecção de ciclo via DFS.',
    whatYouNeedToKnow:
      'DFS explora o mais fundo possível antes de retroceder (backtracking), usando pilha (ou recursão). O professor marca cada vértice com um estado numérico: 0 (não começou), 1 (começou mas não terminou), 2 (terminou) — escrito exatamente assim no quadro. Ao processar as arestas de um vértice em progresso, cada aresta é classificada: árvore (vizinho em estado 0), retorno (vizinho em estado 1 — indica ciclo), avanço ou cruzamento (vizinho em estado 2).',
    understand: [
      'VISITAR_REC(v): marca v como 1; para cada vizinho u: se estado[u]=0, é aresta de ÁRVORE, chama VISITAR_REC(u); se estado[u]=1, é aresta de RETORNO (⇒ HÁ CICLO); se estado[u]=2, é aresta de AVANÇO ou CRUZAMENTO. No fim, marca v como 2.',
      'Aresta de avanço: liga um vértice a um descendente já visitado (pula níveis na árvore de busca). Aresta de cruzamento: liga a um vértice de outro ramo, já totalmente processado.',
      'Em grafo NÃO-DIRIGIDO só existem arestas de árvore e de retorno (avanço e cruzamento não ocorrem).',
      'DFS a partir de v e a coleção de vértices alcançados = fecho transitivo direto de v (ver tópico "Fecho transitivo").',
    ],
    commonPitfall: 'Usar branco/cinza/preto (convenção de livros como Cormen) na resposta em vez dos estados 0/1/2 do professor — funcionalmente equivalente, mas o professor espera a notação dele.',
    conceptConflict: {
      topic: 'Estados de DFS',
      hasRealDifference: true,
      professorDefinition: 'Estados numéricos 0 (não começou) / 1 (em progresso) / 2 (terminou), vistos no quadro.',
      professorSource: { type: 'professor_board', note: 'Fotos de quadro, aula ao vivo' },
      alternatives: [
        { author: 'Cormen', text: 'Coloração branco/cinza/preto + timestamps de descoberta/término — mesma estrutura lógica de 3 estados.' },
        { author: 'Sedgewick', text: 'Usa timestamps pre/post (sem cor nem estado discreto); "em progresso" = pre setado e post não.' },
        { author: 'Kleinberg & Tardos', text: 'Versão simplificada só com booleano "Explorado" — não distingue em-progresso de terminado, não sustenta detecção de ciclo da mesma forma.' },
      ],
      differenceExplanation: 'Mesma lógica de 3 estados que Cormen, só que com números em vez de cores. A versão de Kleinberg & Tardos citada no aulão para o algoritmo básico não é suficiente sozinha para classificar arestas.',
      examGuidance: 'Use a notação 0/1/2 do professor — é a que aparece no quadro (fonte primária) e o que ele espera na resposta.',
    },
    sources: [{ type: 'professor_board', note: 'Fotos de quadro' }, { type: 'professor_support_material', file: 'Resumo Prova 1 Grafos.pdf' }],
  },
  {
    id: 'fecho-transitivo',
    moduleId: 'busca-alcancabilidade',
    order: 3,
    slug: 'fecho-transitivo',
    title: 'Fecho transitivo direto e inverso',
    examLikelihood: 'high',
    examEvidence: 'Fecho transitivo (direto/inverso) em 4 de 8 provas (2022/1, 2022/2, e base de questões de base/anti-base em 2023/2, 2024/1).',
    whatYouNeedToKnow:
      'Fecho transitivo direto de v: todos os vértices alcançáveis a partir de v, via DFS/BFS a partir de v (notação Γ⁺(v)). Fecho transitivo inverso de v: todos os vértices que alcançam v — calculado transpondo o grafo (invertendo todas as arestas) e fazendo DFS/BFS a partir de v no grafo transposto.',
    understand: [
      'Grafo transposto Gᵀ: mesmos vértices, todas as arestas invertidas — (u,v) vira (v,u).',
      'Fecho direto de v = Γ⁺(v) em G. Fecho inverso de v = Γ⁺(v) em Gᵀ.',
      'Não confundir com a matriz de fecho transitivo completa (todos os pares) de Floyd-Warshall/Warshall — a P1 sempre pede o fecho de UM vértice específico, resolvido em O(V+E) por DFS/BFS, não a matriz inteira O(V³).',
    ],
    commonPitfall: 'Calcular o fecho inverso fazendo DFS/BFS no grafo original olhando "para trás" mentalmente, em vez de efetivamente transpor o grafo primeiro — leva a erro em grafos com mais de 4-5 vértices.',
    conceptConflict: {
      topic: 'Fecho transitivo',
      hasRealDifference: true,
      professorDefinition: 'Fecho de UM vértice: Γ⁺(v) via DFS/BFS a partir de v (direto) ou do transposto (inverso).',
      professorSource: { type: 'professor_support_material', file: 'Resumo Prova 1 Grafos.pdf' },
      alternatives: [
        { author: 'Cormen', text: 'Fecho transitivo COMPLETO (todos os pares), O(n³), via Floyd-Warshall adaptado ou multiplicação booleana — não separa "direto/inverso".' },
        { author: 'Sedgewick', text: 'Mesma ideia de Cormen — algoritmo de Warshall detalhado, fecho completo O(V³).' },
      ],
      differenceExplanation: 'O professor pede alcançabilidade a partir de um vértice específico (O(V+E)), os livros clássicos descrevem o fecho completo entre todos os pares (O(V³)) — problemas diferentes.',
      examGuidance: 'Use DFS/BFS a partir do vértice pedido (e do transposto, para o inverso). Não é necessário construir a matriz de Warshall inteira.',
    },
    sources: [{ type: 'professor_support_material', file: 'Resumo Prova 1 Grafos.pdf' }, { type: 'old_exam', file: '2022-1-exam.pdf' }],
  },
  {
    id: 'base-antibase',
    moduleId: 'busca-alcancabilidade',
    order: 4,
    slug: 'base-antibase',
    title: 'Base e anti-base de um grafo dirigido',
    examLikelihood: 'high',
    examEvidence: 'Um dos tópicos mais recorrentes: 4 de 8 provas (2022/1, 2022/2, 2023/2, 2024/1), quase sempre pedindo "algoritmo para identificar base".',
    whatYouNeedToKnow:
      'Base B⊆V de um grafo dirigido: conjunto tal que todo vértice do grafo é alcançável a partir de algum vértice de B (Γ⁺(B)=V), com cardinalidade mínima. Anti-base: definição simétrica — todo vértice alcança algum vértice da anti-base (usa o grafo transposto).',
    understand: [
      'Método do professor: calcule o grau de entrada de todos os vértices. Vértices com grau de entrada 0 não são alcançados por ninguém — são candidatos naturais à base.',
      'Se o grafo tem ciclos: contraia cada ciclo em um hipervértice (equivalente a calcular os componentes fortemente conexos e "condensar" o grafo em um DAG). Quando esse hipervértice tem grau de entrada 0 na condensação, um vértice qualquer do ciclo original entra na base.',
      'Para anti-base: transponha o grafo e aplique o mesmo método.',
      'Em termos de SCC: a base = um representante de cada SCC que tem grau de entrada 0 na condensação (SCC-fonte). A anti-base = um representante de cada SCC-sumidouro (grau de saída 0 na condensação).',
      'Se |BASE| = 1, existe um único vértice "raiz" que alcança todo o grafo.',
    ],
    commonPitfall: 'Esquecer de contrair ciclos antes de olhar o grau de entrada — dentro de um ciclo, todo vértice tem grau de entrada ≥1 mesmo que o ciclo inteiro seja, coletivamente, uma fonte da condensação.',
    conceptConflict: {
      topic: 'Base e anti-base',
      hasRealDifference: true,
      professorDefinition: 'B⊆V com Γ⁺(B)=V, cardinalidade mínima. Calculada via grau de entrada + contração de SCCs.',
      professorSource: { type: 'professor_support_material', file: 'Flash Cards Grafos-1.pdf', note: 'Atribuído a "Jamil, Silvio" no material de monitoria' },
      alternatives: [
        { author: 'Cormen', text: 'Não usa "base"/"anti-base", mas define a condensação G^SCC (grafo de componentes) — a base corresponde exatamente às SCCs-fonte dessa condensação.' },
        { author: 'West', text: 'Define "kernel": conjunto S INDEPENDENTE (sem arestas internas) tal que todo vértice fora de S tem sucessor DIRETO em S — conceito DIFERENTE (exige independência e adjacência direta, não só alcançabilidade).' },
      ],
      differenceExplanation: '"Base"/"anti-base" é terminologia própria do professor. A estrutura equivalente nos livros é a condensação em SCCs (Cormen). Atenção: o "kernel" de West NÃO é sinônimo de base, apesar do nome parecido — não troque um pelo outro.',
      examGuidance: 'Use a notação Γ⁺ e o método do professor (grau de entrada + contração de ciclo/SCC). Não há fonte bibliográfica padrão para citar como alternativa direta.',
    },
    sources: [{ type: 'professor_support_material', file: 'Flash Cards Grafos-1.pdf' }, { type: 'professor_board', note: 'Fotos de quadro' }],
  },
  {
    id: 'deteccao-ciclo',
    moduleId: 'busca-alcancabilidade',
    order: 5,
    slug: 'deteccao-ciclo',
    title: 'Detecção de ciclo em grafo dirigido',
    examLikelihood: 'high',
    examEvidence: '2024/2-Q3 (30%) e 2026/1-Q4 (25%, pedindo DUAS soluções distintas) — tópico de alto peso nas provas mais recentes.',
    whatYouNeedToKnow:
      'Um grafo dirigido tem ciclo ⟺ uma DFS encontra uma aresta de RETORNO (aponta para um vértice em estado 1, "em progresso"). Se não há nenhuma aresta de retorno em nenhuma DFS a partir de todo vértice não visitado, o grafo é acíclico (DAG).',
    understand: [
      'Rode DFS normalmente com os estados 0/1/2. No momento em que uma aresta aponta para um vértice em estado 1, pare: há ciclo, e o ciclo pode ser reconstruído seguindo a pilha de recursão do vértice atual até o vértice destino da aresta de retorno.',
      'Uma segunda estratégia válida (útil quando a prova pede "duas soluções distintas", como em 2026/1-Q4): calcular a ordenação topológica via remoção incremental de vértices de grau de entrada 0 — se sobrar algum vértice sem conseguir grau de entrada 0 (fila esvazia antes de processar todos os vértices), há ciclo.',
      'Grafo acíclico dirigido = DAG. É pré-requisito para ordenação topológica e cálculo de maior caminho.',
    ],
    commonPitfall: 'Confundir aresta de retorno com aresta de avanço/cruzamento — só a aresta de retorno (destino em estado 1) indica ciclo; avanço e cruzamento (destino em estado 2) não indicam ciclo em grafo dirigido.',
    sources: [{ type: 'professor_board', note: 'Fotos de quadro — pseudocódigo VISIT/VISITAR_REC' }],
  },
];
