import type { Question } from '@/content/types';
import { degree, isDegreeSequencePossible, edgeBoundsForComponents } from '@/lib/graph';
import { UG_SIX, UG_SIX_LAID_OUT } from './graphs';

export const fundamentosQuestions: Question[] = [
  {
    id: 'fund-def-01',
    topic: 'definicao-terminologia',
    difficulty: 'easy',
    duration: 'quick',
    examLikelihood: 'high',
    sourceStyle: 'slide',
    type: 'TRUE_FALSE',
    prompt: 'Em um grafo SIMPLES, podem existir arestas paralelas (mais de uma aresta entre o mesmo par de vértices).',
    correctValue: false,
    source: { type: 'professor_slide', file: '01-graphs-concepts.pdf' },
    hints: ['A definição de "grafo simples" exclui duas coisas específicas.', 'Pense em laços e arestas paralelas.'],
    solution: 'Grafo simples = sem laços E sem arestas paralelas. Se houver mais de uma aresta entre o mesmo par de vértices, o grafo é um multigrafo, não simples.',
  },
  {
    id: 'fund-def-02',
    topic: 'definicao-terminologia',
    difficulty: 'easy',
    duration: 'quick',
    examLikelihood: 'medium',
    sourceStyle: 'generated',
    type: 'MULTIPLE_CHOICE',
    prompt: 'Um vértice com grau exatamente 1 é chamado de:',
    options: [
      { id: 'a', label: 'Vértice isolado' },
      { id: 'b', label: 'Vértice pendente' },
      { id: 'c', label: 'Vértice regular' },
      { id: 'd', label: 'Vértice central' },
    ],
    correctOptionId: 'b',
    source: { type: 'professor_slide', file: '01-graphs-concepts.pdf' },
    hints: ['Vértice isolado tem grau 0.', 'O termo lembra algo "pendurado" por uma única conexão.'],
    solution: 'Vértice pendente (ou "folha", em árvores) é aquele com grau exatamente 1. Vértice isolado tem grau 0.',
  },
  {
    id: 'fund-def-03',
    topic: 'definicao-terminologia',
    difficulty: 'easy',
    duration: 'quick',
    examLikelihood: 'medium',
    sourceStyle: 'generated',
    type: 'NUMBER_INPUT',
    prompt: 'No grafo abaixo, qual o grau do vértice f?',
    displayGraphs: { a: UG_SIX_LAID_OUT },
    correctNumber: degree(UG_SIX, 'f'),
    source: { type: 'professor_support_material', note: 'Grafo gerado, formato consistente com exercícios do professor' },
    hints: ['Conte quantas arestas tocam f no desenho.'],
    solution: `d(f) = ${degree(UG_SIX, 'f')} — f só é incidente a uma aresta (e-f), logo é um vértice pendente.`,
  },
  {
    id: 'fund-def-04',
    topic: 'definicao-terminologia',
    difficulty: 'medium',
    duration: 'quick',
    examLikelihood: 'medium',
    sourceStyle: 'generated',
    type: 'GRAPH_SELECT_VERTEX',
    prompt: 'Selecione todos os vértices com grau ímpar no grafo abaixo.',
    graph: UG_SIX_LAID_OUT,
    multi: true,
    correctVertexIds: UG_SIX.vertices.filter((v) => degree(UG_SIX, v.id) % 2 !== 0).map((v) => v.id),
    source: { type: 'professor_support_material' },
    hints: ['Calcule o grau de cada vértice contando arestas incidentes.', 'Pelo teorema do aperto de mãos, o número de vértices de grau ímpar é sempre par — use isso para conferir sua resposta.'],
    solution: `Graus: ${UG_SIX.vertices.map((v) => `${v.label}=${degree(UG_SIX, v.id)}`).join(', ')}. Vértices de grau ímpar: ${UG_SIX.vertices.filter((v) => degree(UG_SIX, v.id) % 2 !== 0).map((v) => v.label).join(', ')}.`,
  },
  {
    id: 'fund-walk-01',
    topic: 'passeios-caminhos-ciclos',
    difficulty: 'medium',
    duration: 'quick',
    examLikelihood: 'medium',
    sourceStyle: 'slide',
    type: 'MULTIPLE_CHOICE',
    prompt: 'Qual sequência de vértices/arestas pode repetir vértices E arestas livremente?',
    options: [
      { id: 'a', label: 'Path (caminho)' },
      { id: 'b', label: 'Trail (trilha)' },
      { id: 'c', label: 'Walk (passeio)' },
      { id: 'd', label: 'Cycle (ciclo)' },
    ],
    correctOptionId: 'c',
    source: { type: 'professor_slide', file: '01-graphs-concepts.pdf' },
    hints: ['Walk é o mais "permissivo" dos quatro — sem nenhuma restrição de repetição.'],
    solution: 'Walk (passeio) não tem restrição. Trail não repete aresta. Path não repete vértice. Cycle é um passeio fechado sem repetição (exceto início=fim).',
  },
  {
    id: 'fund-walk-02',
    topic: 'passeios-caminhos-ciclos',
    difficulty: 'easy',
    duration: 'quick',
    examLikelihood: 'medium',
    sourceStyle: 'generated',
    type: 'TRUE_FALSE',
    prompt: 'O número mínimo de arestas para um grafo com n vértices ser conexo é n − 1.',
    correctValue: true,
    source: { type: 'professor_support_material', file: 'Resumo Prova 1 Grafos.pdf' },
    hints: ['Pense em uma árvore — a estrutura conexa com o menor número possível de arestas.'],
    solution: 'Correto — essa é a definição de árvore geradora: n vértices conectados com exatamente n−1 arestas, sem nenhuma aresta "sobrando".',
  },
  {
    id: 'fund-walk-03',
    examFamily: 'bipartido-tripartido',
    topic: 'passeios-caminhos-ciclos',
    difficulty: 'medium',
    duration: 'normal',
    examLikelihood: 'medium',
    sourceStyle: 'old_exam',
    type: 'NUMBER_INPUT',
    prompt: 'Qual o número máximo de arestas de um grafo bipartido completo K(m,n) com m=4 e n=5?',
    correctNumber: 4 * 5,
    unit: 'arestas',
    source: { type: 'old_exam', file: '2023-1-exam.pdf' },
    hints: ['Em um bipartido completo, toda combinação entre os dois lados vira uma aresta.', '|E| = m·n.'],
    solution: 'K(4,5) tem |E| = m·n = 4·5 = 20 arestas — toda combinação de um vértice de cada lado forma uma aresta.',
  },
  {
    id: 'fund-fam-01',
    topic: 'aperto-de-maos-familias',
    difficulty: 'easy',
    duration: 'quick',
    examLikelihood: 'high',
    sourceStyle: 'generated',
    type: 'NUMBER_INPUT',
    prompt: 'Um grafo tem 7 vértices, todos de grau 4. Quantas arestas ele tem?',
    correctNumber: (7 * 4) / 2,
    unit: 'arestas',
    source: { type: 'professor_slide', file: '01-graphs-concepts.pdf' },
    hints: ['Teorema do aperto de mãos: soma dos graus = 2|E|.', 'Some todos os graus e divida por 2.'],
    solution: `Σd(v) = 7×4 = 28 = 2|E| ⇒ |E| = ${(7 * 4) / 2}.`,
  },
  {
    id: 'fund-fam-02',
    examFamily: 'limites-grau-arestas',
    topic: 'aperto-de-maos-familias',
    difficulty: 'hard',
    duration: 'normal',
    examLikelihood: 'high',
    sourceStyle: 'old_exam',
    type: 'MULTIPLE_CHOICE',
    prompt: 'A sequência de graus (1, 1, 3, 3, 3, 3, 5, 6, 8, 9) — sobre 10 vértices de um grafo simples — pode representar um grafo?',
    options: [
      { id: 'a', label: 'Sim, a sequência é graficável' },
      { id: 'b', label: 'Não — a soma dos graus é ímpar' },
      { id: 'c', label: 'Não — grau 0 e grau 9 coexistem' },
      { id: 'd', label: 'Não — mesmo com soma par e valores no intervalo [0,9], viola o critério de Erdős–Gallai' },
    ],
    correctOptionId: 'd',
    source: { type: 'old_exam', file: '2023-1-exam.pdf' },
    hints: [
      `A soma é ${[1, 1, 3, 3, 3, 3, 5, 6, 8, 9].reduce((a, b) => a + b, 0)} (par) e todos os valores estão entre 0 e 9 — essas checagens rápidas não bastam aqui.`,
      'Ordene decrescente e compare a soma dos k maiores graus com k(k−1) + soma dos min(dᵢ,k) dos demais, para k=1,2,3...',
      isDegreeSequencePossible([1, 1, 3, 3, 3, 3, 5, 6, 8, 9], 10).reason,
    ],
    solution: `${isDegreeSequencePossible([1, 1, 3, 3, 3, 3, 5, 6, 8, 9], 10).reason} Isso mostra que soma par + intervalo válido NÃO bastam para garantir que uma sequência é graficável — é preciso o critério completo de Erdős–Gallai (ou tentar construir o grafo diretamente e travar).`,
  },
  {
    id: 'fund-fam-03',
    examFamily: 'possibilidade-n-k',
    topic: 'aperto-de-maos-familias',
    difficulty: 'medium',
    duration: 'quick',
    examLikelihood: 'high',
    sourceStyle: 'old_exam',
    type: 'SHORT_ANSWER',
    prompt: 'Um grafo simples tem 11 vértices e 6 componentes conexos. Qual o número MÍNIMO de arestas possível? (responda só o número)',
    acceptedAnswers: [String(edgeBoundsForComponents(11, 6).min)],
    source: { type: 'old_exam', file: '2022-2-exam.pdf' },
    hints: ['Cada componente, no mínimo, é uma árvore (n_i − 1 arestas).', 'Some (n_i − 1) sobre os 6 componentes — o total dá n − k.'],
    solution: `m_min = n − k = 11 − 6 = ${edgeBoundsForComponents(11, 6).min}.`,
  },
  {
    id: 'fund-fam-04',
    examFamily: 'possibilidade-n-k',
    topic: 'aperto-de-maos-familias',
    difficulty: 'hard',
    duration: 'normal',
    examLikelihood: 'high',
    sourceStyle: 'old_exam',
    type: 'NUMBER_INPUT',
    prompt: 'Mesmo grafo: 11 vértices, 6 componentes conexos. Qual o número MÁXIMO de arestas possível?',
    correctNumber: edgeBoundsForComponents(11, 6).max,
    source: { type: 'old_exam', file: '2022-2-exam.pdf' },
    hints: ['O máximo ocorre quando 5 componentes são vértices isolados e o 6º concentra todos os vértices "sobrando" como grafo completo.', `m_max = (n−k)(n−k+1)/2.`],
    solution: `Concentre os vértices "livres" (n−k+1 = 6) em um único componente completo: m_max = (n−k)(n−k+1)/2 = 5×6/2 = ${edgeBoundsForComponents(11, 6).max}.`,
  },
  {
    id: 'fund-fam-05',
    examFamily: 'pombos',
    topic: 'aperto-de-maos-familias',
    difficulty: 'medium',
    duration: 'deep',
    examLikelihood: 'high',
    sourceStyle: 'old_exam',
    type: 'PROOF_OR_JUSTIFICATION',
    prompt: 'Prove que todo grafo simples com n ≥ 2 vértices possui pelo menos dois vértices de mesmo grau.',
    rubric: [
      'Observa que o grau de um vértice varia no intervalo [0, n−1]',
      'Observa que grau 0 e grau n−1 não podem coexistir no mesmo grafo simples',
      'Conclui que há no máximo n−1 valores de grau possíveis para n vértices',
      'Aplica o princípio da casa dos pombos para concluir que dois vértices compartilham o mesmo grau',
    ],
    source: { type: 'old_exam', file: '2024-2-exam.pdf' },
    professorStyleSimilarity: 'high',
    hints: [
      'Quantos valores de grau são POSSÍVEIS em um grafo simples de n vértices?',
      'Grau 0 (isolado) e grau n−1 (ligado a todos) não podem existir ao mesmo tempo — por quê?',
      'Se há n vértices mas no máximo n−1 valores de grau possíveis, o que o princípio da casa dos pombos garante?',
    ],
    solution:
      'Em um grafo simples de n vértices, o grau de qualquer vértice está entre 0 e n−1. Se algum vértice tem grau n−1, ele está ligado a todos os outros — logo nenhum vértice pode ter grau 0 (todos têm pelo menos essa aresta). Isso significa que 0 e n−1 nunca ocorrem juntos, restando no máximo n−1 valores possíveis de grau para distribuir entre n vértices. Pelo princípio da casa dos pombos, pelo menos dois vértices devem compartilhar o mesmo grau. (Questão praticamente fixa nas provas de 2024/1, 2024/2 e 2026/1 — decore esta prova.)',
  },
];
