import type { Question } from '@/content/types';
import { adjacencyMatrix, incidenceMatrix, adjacencyList } from '@/lib/graph';
import { UG_SIX, UG_SIX_LAID_OUT, DG_CYCLE } from './graphs';

const ugAdj = adjacencyMatrix(UG_SIX);
const ugAdjCells: Record<string, number> = {};
ugAdj.rowIds.forEach((r, i) => ugAdj.colIds.forEach((c, j) => (ugAdjCells[`${r}|${c}`] = ugAdj.matrix[i][j])));

const dgInc = incidenceMatrix(DG_CYCLE);
const dgIncCells: Record<string, number> = {};
dgInc.rowIds.forEach((r, i) => dgInc.colIds.forEach((c, j) => (dgIncCells[`${r}|${c}`] = dgInc.matrix[i][j])));

const ugList = adjacencyList(UG_SIX);

export const representacoesQuestions: Question[] = [
  {
    id: 'rep-adj-01',
    topic: 'matriz-adjacencia',
    difficulty: 'easy',
    duration: 'quick',
    examLikelihood: 'high',
    sourceStyle: 'generated',
    type: 'TRUE_FALSE',
    prompt: 'A matriz de adjacência de um grafo NÃO-dirigido é sempre simétrica.',
    correctValue: true,
    source: { type: 'professor_slide', file: '04-graphs-data-structures.pdf' },
    hints: ['Se existe aresta {u,v}, ela "vale" nos dois sentidos.'],
    solution: 'Em grafo não-dirigido, {u,v} é a mesma aresta de {v,u}, então A[u][v]=A[v][u] sempre — matriz simétrica.',
  },
  {
    id: 'rep-adj-02',
    topic: 'matriz-adjacencia',
    difficulty: 'medium',
    duration: 'normal',
    examLikelihood: 'high',
    sourceStyle: 'generated',
    type: 'MATRIX_FILL',
    matrixKind: 'adjacency',
    prompt: 'Preencha a matriz de adjacência do grafo abaixo.',
    graph: UG_SIX_LAID_OUT,
    rowIds: ugAdj.rowIds,
    colIds: ugAdj.colIds,
    correctCells: ugAdjCells,
    source: { type: 'professor_slide', file: '04-graphs-data-structures.pdf' },
    hints: ['Para cada aresta {u,v}, marque 1 em [u][v] E em [v][u].', 'A diagonal principal fica 0 (não há laços neste grafo).'],
    solution: 'Cada entrada A[i][j] = número de arestas entre i e j (0 ou 1, já que o grafo é simples). Lembre-se de espelhar: não-dirigido é simétrico.',
  },
  {
    id: 'rep-adj-03',
    topic: 'matriz-adjacencia',
    difficulty: 'easy',
    duration: 'quick',
    examLikelihood: 'medium',
    sourceStyle: 'old_exam',
    type: 'SHORT_ANSWER',
    prompt: 'Em uma matriz de adjacência de grafo DIRIGIDO, o que representa a soma dos valores de uma COLUNA j?',
    acceptedAnswers: ['grau de entrada', 'grau de entrada de j', 'in-degree', 'grau de entrada do vertice j'],
    source: { type: 'old_exam', file: '2023-1-exam.pdf' },
    hints: ['Cada linha i representa as arestas que SAEM de i.', 'Uma coluna j acumula, de todas as linhas, quantas arestas CHEGAM em j.'],
    solution: 'A soma da coluna j conta quantas arestas (i,j) existem para algum i — ou seja, o grau de entrada d⁻(j).',
  },
  {
    id: 'rep-inc-01',
    topic: 'matriz-incidencia',
    difficulty: 'medium',
    duration: 'normal',
    examLikelihood: 'medium',
    sourceStyle: 'generated',
    type: 'MATRIX_FILL',
    matrixKind: 'incidence',
    prompt: 'Preencha a matriz de incidência do grafo dirigido abaixo (convenção: +1 na origem, −1 no destino).',
    graph: DG_CYCLE,
    rowIds: dgInc.rowIds,
    colIds: dgInc.colIds,
    correctCells: dgIncCells,
    source: { type: 'professor_slide', file: '04-graphs-data-structures.pdf' },
    hints: ['Cada coluna representa 1 aresta — só duas linhas daquela coluna são não-nulas (origem e destino).', 'Origem recebe +1, destino recebe −1.'],
    solution: 'Cada coluna corresponde a uma aresta (origem,destino): +1 na linha de origem, −1 na linha de destino, 0 nas demais linhas.',
  },
  {
    id: 'rep-inc-02',
    topic: 'matriz-incidencia',
    difficulty: 'easy',
    duration: 'quick',
    examLikelihood: 'medium',
    sourceStyle: 'generated',
    type: 'SHORT_ANSWER',
    prompt: 'Uma matriz de incidência de grafo dirigido tem dimensão n×m. O que representa m?',
    acceptedAnswers: ['numero de arestas', 'numero de arestas do grafo', 'quantidade de arestas', 'o numero de arestas', '|e|'],
    source: { type: 'professor_slide', file: '04-graphs-data-structures.pdf' },
    hints: ['n é o número de vértices (linhas). E as colunas?'],
    solution: 'Cada COLUNA da matriz de incidência representa uma aresta — logo m = |E|, o número de arestas do grafo.',
  },
  {
    id: 'rep-list-01',
    topic: 'lista-adjacencia',
    difficulty: 'easy',
    duration: 'quick',
    examLikelihood: 'high',
    sourceStyle: 'generated',
    type: 'ADJACENCY_LIST_FILL',
    prompt: 'Preencha a lista de adjacência (vizinhos) de cada vértice do grafo abaixo.',
    graph: UG_SIX_LAID_OUT,
    correctList: ugList.successorsMap,
    source: { type: 'professor_slide', file: '04-graphs-data-structures.pdf' },
    hints: ['Digite os vizinhos separados por vírgula, ex.: b, c.', 'Em grafo não-dirigido, se a está na lista de b, então b também está na lista de a.'],
    solution: `Lista de adjacência: ${Object.entries(ugList.successorsMap).map(([v, n]) => `${v}: {${n.join(', ')}}`).join(' — ')}.`,
  },
  {
    id: 'rep-list-02',
    topic: 'lista-adjacencia',
    difficulty: 'medium',
    duration: 'quick',
    examLikelihood: 'high',
    sourceStyle: 'generated',
    type: 'TRUE_FALSE',
    prompt: 'Em um grafo dirigido, se b está na lista de sucessores de a, então a está necessariamente na lista de sucessores de b.',
    correctValue: false,
    source: { type: 'professor_slide', file: '04-graphs-data-structures.pdf' },
    hints: ['Pense em uma aresta de mão única (a→b) sem a aresta de volta (b→a).'],
    solution: 'Falso — arestas dirigidas têm sentido único. (a→b) na lista de sucessores de a não implica (b→a).',
  },
  {
    id: 'rep-list-03',
    topic: 'lista-adjacencia',
    difficulty: 'medium',
    duration: 'quick',
    examLikelihood: 'medium',
    sourceStyle: 'generated',
    type: 'MULTIPLE_CHOICE',
    prompt: 'Para um grafo ESPARSO (poucas arestas em relação a n²), qual representação usa MENOS memória?',
    options: [
      { id: 'a', label: 'Matriz de adjacência — O(n²) sempre' },
      { id: 'b', label: 'Lista de adjacência — O(n+m)' },
      { id: 'c', label: 'Ambas usam exatamente a mesma memória' },
      { id: 'd', label: 'Matriz de incidência — O(n·m) é sempre menor' },
    ],
    correctOptionId: 'b',
    source: { type: 'professor_slide', file: '04-graphs-data-structures.pdf' },
    hints: ['Matriz de adjacência gasta n² independente do número de arestas.', 'Lista de adjacência só guarda o que realmente existe.'],
    solution: 'Lista de adjacência é O(n+m) — cresce com o número real de arestas, ideal para grafos esparsos. Matriz de adjacência sempre gasta O(n²), mesmo com poucas arestas.',
  },
];
