import type { Question } from '@/content/types';
import { isSelfComplementary, numberOfSubgraphsOfCompleteGraph, isomorphismNecessaryConditions } from '@/lib/graph';
import { UG_SIX_ISO_A, UG_SIX_ISO_B, NON_ISO_A, NON_ISO_B } from './graphs';
import { makeGraph } from '@/lib/graph';

const K4 = makeGraph(false, ['1', '2', '3', '4'], [
  ['1', '2'],
  ['1', '3'],
  ['1', '4'],
  ['2', '3'],
  ['2', '4'],
  ['3', '4'],
]);

// P4 (caminho de 4 vértices) é o menor grafo auto-complementar não-trivial.
const P4 = makeGraph(false, ['1', '2', '3', '4'], [
  ['1', '2'],
  ['2', '3'],
  ['3', '4'],
]);

export const isomorfismoQuestions: Question[] = [
  {
    id: 'iso-01',
    topic: 'isomorfismo',
    difficulty: 'medium',
    duration: 'quick',
    examLikelihood: 'high',
    sourceStyle: 'generated',
    type: 'TRUE_FALSE',
    prompt: 'Se dois grafos têm o mesmo número de vértices, o mesmo número de arestas e a mesma sequência de graus, então eles são necessariamente isomorfos.',
    correctValue: false,
    source: { type: 'professor_slide', file: '05-graphs-isomorphism-and-concepts.pdf' },
    hints: ['Essas são condições NECESSÁRIAS — o slide do professor é explícito sobre isso.', 'Existem pares de grafos que satisfazem tudo isso e ainda assim não são isomorfos (ex.: um tem triângulo, o outro não).'],
    solution: 'Falso. |V|, |E| e sequência de graus iguais são condições necessárias, mas não suficientes — dois grafos podem satisfazer tudo isso e não serem isomorfos (ex.: diferirem no número de triângulos).',
  },
  {
    id: 'iso-02',
    topic: 'isomorfismo',
    difficulty: 'hard',
    duration: 'deep',
    examLikelihood: 'high',
    sourceStyle: 'generated',
    type: 'ISOMORPHISM_MAPPING',
    prompt: 'Encontre uma bijeção entre os vértices de A e B que preserve todas as adjacências (clique num vértice de A e depois no correspondente em B).',
    graphA: UG_SIX_ISO_A,
    graphB: UG_SIX_ISO_B,
    isIsomorphic: true,
    correctMapping: { '1': 'w', '2': 'x', '3': 'y', '4': 'z' },
    source: { type: 'professor_slide', file: '05-graphs-isomorphism-and-concepts.pdf' },
    hints: ['Ambos são ciclos de 4 vértices (C4) — todo vértice tem grau 2.', 'Mapeie seguindo a ordem do ciclo: se 1-2-3-4-1 é o ciclo em A, procure o ciclo equivalente em B.'],
    solution: 'Os dois grafos são C4 (ciclo de 4 vértices). Qualquer bijeção que preserve a ordem cíclica funciona, ex.: 1→w, 2→x, 3→y, 4→z (seguindo 1-2-3-4-1 e w-x-y-z-w).',
  },
  {
    id: 'iso-03',
    topic: 'isomorfismo',
    difficulty: 'hard',
    duration: 'deep',
    examLikelihood: 'high',
    sourceStyle: 'generated',
    type: 'TRUE_FALSE',
    prompt: 'Os grafos A e B abaixo têm exatamente o mesmo número de vértices (6), o mesmo número de arestas (7) e a mesma sequência de graus. Ainda assim, eles são isomorfos?',
    displayGraphs: { a: NON_ISO_A, b: NON_ISO_B },
    correctValue: false,
    source: { type: 'professor_slide', file: '05-graphs-isomorphism-and-concepts.pdf' },
    professorStyleSimilarity: 'high',
    hints: [
      `Confira: ${JSON.stringify(isomorphismNecessaryConditions(NON_ISO_A, NON_ISO_B).reasons)}`,
      'As condições necessárias batem — então tente ir além: procure um "invariante" mais fino, como a existência de triângulos.',
      'Conte quantos triângulos (3 vértices mutuamente ligados) existem em cada grafo.',
    ],
    solution:
      'Não são isomorfos, apesar de |V|, |E| e sequência de graus baterem (condições necessárias satisfeitas, mas não suficientes). O grafo A tem 2 triângulos (dois triângulos ligados por uma aresta); o grafo B não tem NENHUM triângulo (é um ciclo de 6 vértices com uma aresta a mais ligando dois vértices opostos, formando dois ciclos de 4). Número de triângulos é um invariante de isomorfismo — se difere, os grafos não podem ser isomorfos.',
  },
  {
    id: 'iso-04',
    examFamily: 'isomorfismo-dirigido',
    topic: 'isomorfismo',
    difficulty: 'medium',
    duration: 'deep',
    examLikelihood: 'high',
    sourceStyle: 'old_exam',
    type: 'PROOF_OR_JUSTIFICATION',
    prompt:
      'Transponha a definição de isomorfismo de grafos não-direcionados para grafos direcionados, explicando as diferenças necessárias, e apresente um exemplo de dois grafos direcionados com mais de 5 vértices e 6 arestas que sejam isomorfos entre si.',
    rubric: [
      'Define bijeção f:V(G)→V(H)',
      'Exige preservação de DIREÇÃO: (u,v)∈E(G) ⟺ (f(u),f(v))∈E(H), não só adjacência',
      'Observa que, ao contrário do caso não-dirigido, a ordem do par importa',
      'Constrói um exemplo concreto com mais de 5 vértices e 6 arestas',
      'Verifica explicitamente que a bijeção escolhida preserva todas as 6 arestas',
    ],
    source: { type: 'old_exam', file: '2022-1-exam.pdf' },
    professorStyleSimilarity: 'high',
    hints: [
      'No caso não-dirigido, a definição usa {u,v}∈E(G) ⟺ {f(u),f(v)}∈E(H). O que muda para pares ORDENADOS?',
      'Lembre-se: (u,v) é diferente de (v,u) em grafo dirigido — a bijeção precisa respeitar isso.',
      'Para o exemplo, pode usar um ciclo dirigido de 6 vértices (6 arestas) e "girar" os rótulos.',
    ],
    solution:
      'G e H (dirigidos) são isomorfos se existe bijeção f:V(G)→V(H) tal que (u,v)∈E(G) ⟺ (f(u),f(v))∈E(H) — a MESMA ideia do caso não-dirigido, mas agora a direção do par importa: não basta {f(u),f(v)} existir como aresta, precisa existir NA MESMA DIREÇÃO. Exemplo: G = ciclo dirigido a→b→c→d→e→f→a (6 vértices, 6 arestas); H = ciclo dirigido 1→2→3→4→5→6→1. A bijeção f(a)=1, f(b)=2, ..., f(f)=6 preserva todas as 6 arestas na mesma direção.',
  },
  {
    id: 'comp-01',
    examFamily: 'auto-complementar',
    topic: 'complemento-subgrafo',
    difficulty: 'easy',
    duration: 'quick',
    examLikelihood: 'high',
    sourceStyle: 'generated',
    type: 'NUMBER_INPUT',
    prompt: 'Se um grafo G com 8 vértices tem 12 arestas, quantas arestas tem o complemento Ḡ?',
    correctNumber: (8 * 7) / 2 - 12,
    source: { type: 'professor_slide', file: '05-graphs-isomorphism-and-concepts.pdf' },
    hints: ['|E(G)| + |E(Ḡ)| = |E(K8)| = n(n−1)/2.', 'K8 tem 8×7/2 = 28 arestas no total.'],
    solution: `|E(Ḡ)| = C(8,2) − |E(G)| = 28 − 12 = ${(8 * 7) / 2 - 12}.`,
  },
  {
    id: 'comp-02',
    examFamily: 'auto-complementar',
    topic: 'complemento-subgrafo',
    difficulty: 'medium',
    duration: 'quick',
    examLikelihood: 'high',
    sourceStyle: 'generated',
    type: 'TRUE_FALSE',
    prompt: 'O grafo P4 (caminho simples com 4 vértices: 1-2-3-4) é auto-complementar.',
    displayGraphs: { a: P4 },
    correctValue: isSelfComplementary(P4),
    source: { type: 'professor_support_material', file: 'Lista-de-exercicios-1.pdf' },
    hints: ['Desenhe o complemento de P4 e compare a forma — ele também deve ter 3 arestas (metade de C(4,2)=6).', 'Verifique se existe uma bijeção entre P4 e seu complemento.'],
    solution: `P4 tem 3 arestas; C(4,2)/2 = 3 — a contagem bate. O complemento de 1-2-3-4 é o grafo com arestas {1-3, 2-4, 1-4}\\{já contadas}... na prática, Ḡ de P4 também é um P4 (com outra rotulação): 3-1-4-2. Logo P4 É auto-complementar — é o menor exemplo não-trivial (n=4, o menor n≡0 ou 1 mod 4 maior que 1).`,
  },
  {
    id: 'comp-03',
    examFamily: 'auto-complementar',
    topic: 'complemento-subgrafo',
    difficulty: 'hard',
    duration: 'deep',
    examLikelihood: 'high',
    sourceStyle: 'old_exam',
    type: 'PROOF_OR_JUSTIFICATION',
    prompt:
      'Seja G = (V, E) um grafo simples não-direcionado. O complemento de G, denotado por Ḡ = (V′, E′), é definido por V′ = V e E′ = {{u, v} | {u, v} ∉ E}. Um grafo é dito auto-complementar se é isomorfo ao seu complemento. É correto afirmar que o número de arestas de um grafo auto-complementar é divisível por 4? Justifique sua resposta.',
    rubric: [
      'Responde NÃO (a afirmação é falsa)',
      'Usa que G ≅ Ḡ implica |E(G)| = |E(Ḡ)|',
      'Usa que |E(G)| + |E(Ḡ)| = n(n−1)/2 (as arestas de Kn se dividem entre G e Ḡ)',
      'Deduz |E(G)| = n(n−1)/4 — o que é divisível por 4 é n(n−1), não |E|',
      'Dá contra-exemplo: C5 é auto-complementar com 5 arestas (ou P4 com 3)',
      'Bônus: conclui que n = 4k ou 4k + 1',
    ],
    source: { type: 'old_exam', file: '2025-1-exam.pdf', note: 'Q2 (20%) — enunciado literal; 2022/2-Q4 e 2023/1-Q3 são a mesma família' },
    professorStyleSimilarity: 'high',
    hints: [
      'Se G é auto-complementar, G ≅ Ḡ, logo |E(G)| = |E(Ḡ)|.',
      'Some as arestas de G e Ḡ: juntas formam o grafo completo Kn.',
      'Teste com o menor exemplo que você conhece: quantas arestas tem C5?',
    ],
    solution:
      'Não. Como G ≅ Ḡ, |E(G)| = |E(Ḡ)|. Toda aresta de Kn está em G ou em Ḡ (nunca nos dois), então |E(G)| + |E(Ḡ)| = n(n−1)/2; substituindo, 2|E(G)| = n(n−1)/2 e |E(G)| = n(n−1)/4. Isso mostra que n(n−1) é divisível por 4 (logo n = 4k ou 4k + 1), mas NÃO que |E(G)| seja: C5 (ciclo com 5 vértices) é auto-complementar e tem 5·4/4 = 5 arestas; P4 tem 3. A afirmação é falsa. Na prova, escreva a dedução inteira e o contra-exemplo — só a fórmula não vale (anotação de correção em 2022/2-Q5b).',
  },
  {
    id: 'sub-01',
    examFamily: 'subgrafos-kn',
    topic: 'complemento-subgrafo',
    difficulty: 'medium',
    duration: 'normal',
    examLikelihood: 'high',
    sourceStyle: 'old_exam',
    type: 'NUMBER_INPUT',
    prompt: 'Quantos subgrafos (não vazios) tem o grafo completo K4?',
    displayGraphs: { a: K4 },
    correctNumber: numberOfSubgraphsOfCompleteGraph(4),
    source: { type: 'old_exam', file: '2022-2-exam.pdf' },
    hints: ['Fórmula: Σ_{i=1}^{n} C(n,i)·2^(i(i−1)/2) — escolhe i vértices, depois decide quais das C(i,2) arestas entre eles incluir.', 'Para n=4: some as contribuições de i=1 até i=4.'],
    solution: `Σ_{i=1}^{4} C(4,i)·2^(i(i−1)/2) = C(4,1)·1 + C(4,2)·2 + C(4,3)·8 + C(4,4)·64 = 4 + 12 + 32 + 64 = ${numberOfSubgraphsOfCompleteGraph(4)}.`,
  },
  {
    id: 'sub-02',
    topic: 'teoremas-contagem',
    difficulty: 'easy',
    duration: 'quick',
    examLikelihood: 'high',
    sourceStyle: 'generated',
    type: 'SHORT_ANSWER',
    prompt: 'Complete: para um grafo simples com n vértices e k componentes conexos, o número mínimo de arestas é n menos ___.',
    acceptedAnswers: ['k', 'o numero de componentes'],
    source: { type: 'professor_support_material', file: 'Resumo Prova 1 Grafos.pdf' },
    hints: ['Um componente conexo com n_i vértices precisa de pelo menos n_i − 1 arestas.'],
    solution: 'm_min = n − k: cada um dos k componentes, com n_i vértices, precisa de pelo menos n_i − 1 arestas para ser conexo; somando sobre os componentes, Σ(n_i − 1) = n − k.',
  },
];
