import type { Question } from '@/content/types';
import { bfs, dfs, transitiveClosureDirect, transitiveClosureInverse, baseAndAntiBase } from '@/lib/graph';
import { UG_SIX, UG_SIX_LAID_OUT, DG_CYCLE, PROFESSOR_SCC_EXAMPLE } from './graphs';

const bfsFromA = bfs(UG_SIX, 'a');
const dfsCycle = dfs(DG_CYCLE);
const backEdgeId = Object.entries(dfsCycle.edgeClass).find(([, cls]) => cls === 'back')![0];
const scc = baseAndAntiBase(PROFESSOR_SCC_EXAMPLE);

export const buscaQuestions: Question[] = [
  {
    id: 'bfs-01',
    topic: 'bfs',
    difficulty: 'easy',
    duration: 'quick',
    examLikelihood: 'high',
    sourceStyle: 'generated',
    type: 'TRUE_FALSE',
    prompt: 'BFS usa uma estrutura de fila (FIFO — primeiro a entrar, primeiro a sair).',
    correctValue: true,
    source: { type: 'professor_support_material', file: 'Resumo Prova 1 Grafos.pdf' },
    hints: ['Pense em como a busca avança "em camadas".'],
    solution: 'Correto — BFS usa fila. É essa estrutura que garante a exploração em camadas de distância crescente.',
  },
  {
    id: 'bfs-02',
    examFamily: 'bfs-distancias',
    topic: 'bfs',
    difficulty: 'medium',
    duration: 'normal',
    examLikelihood: 'high',
    sourceStyle: 'old_exam',
    type: 'ORDERING',
    prompt: 'Ordene os vértices na ordem em que uma BFS a partir de "a" os remove da fila (prioridade alfabética entre vizinhos empatados).',
    displayGraphs: { a: UG_SIX_LAID_OUT },
    items: UG_SIX.vertices.map((v) => ({ id: v.id, label: v.label })).sort(() => Math.random() - 0.5),
    correctOrder: bfsFromA.order,
    source: { type: 'old_exam', file: '2023-1-exam.pdf' },
    professorStyleSimilarity: 'high',
    hints: ['Comece em a (distância 0), depois todos os vizinhos diretos de a (distância 1), em ordem alfabética.', `Distâncias calculadas: ${JSON.stringify(bfsFromA.distances)}.`],
    solution: `Ordem de saída da fila (BFS a partir de a): ${bfsFromA.order.join(' → ')}. Distâncias: ${Object.entries(bfsFromA.distances).map(([v, d]) => `${v}=${d}`).join(', ')}.`,
  },
  {
    id: 'bfs-03',
    examFamily: 'bfs-distancias',
    topic: 'bfs',
    difficulty: 'easy',
    duration: 'quick',
    examLikelihood: 'medium',
    sourceStyle: 'generated',
    type: 'NUMBER_INPUT',
    prompt: 'Qual a distância (nº de arestas do caminho mais curto) de "a" até "f" no grafo abaixo?',
    displayGraphs: { a: UG_SIX_LAID_OUT },
    correctNumber: bfsFromA.distances.f,
    source: { type: 'professor_support_material' },
    hints: ['Rode BFS a partir de a e observe em que "camada" f aparece.'],
    solution: `Distância(a,f) = ${bfsFromA.distances.f} — caminho a→b→d→e→f (ou similar de mesmo tamanho).`,
  },
  {
    id: 'dfs-01',
    topic: 'dfs-classificacao',
    difficulty: 'medium',
    duration: 'quick',
    examLikelihood: 'high',
    sourceStyle: 'generated',
    type: 'TRUE_FALSE',
    prompt: 'Em um grafo NÃO-DIRIGIDO, uma DFS pode produzir arestas de avanço e de cruzamento.',
    correctValue: false,
    source: { type: 'professor_slide' },
    hints: ['Pense em como, num grafo não-dirigido, toda aresta "não-árvore" conecta um vértice a um ancestral seu.'],
    solution: 'Falso — em grafo não-dirigido só existem arestas de árvore e de retorno. Isso ocorre porque, ao explorar uma aresta {u,v} onde v já foi visitado, v é necessariamente ancestral de u na árvore de busca (não pode ser um "primo" ou descendente, dada a simetria da aresta).',
  },
  {
    id: 'dfs-02',
    examFamily: 'ciclo-dfs-scc',
    topic: 'dfs-classificacao',
    difficulty: 'hard',
    duration: 'normal',
    examLikelihood: 'high',
    sourceStyle: 'old_exam',
    type: 'GRAPH_SELECT_EDGE',
    prompt: 'Rodando DFS a partir de "a" (prioridade alfabética) no grafo dirigido abaixo, selecione a(s) aresta(s) de RETORNO.',
    graph: DG_CYCLE,
    correctEdgeIds: [backEdgeId],
    source: { type: 'old_exam', file: '2022-2-exam.pdf' },
    professorStyleSimilarity: 'high',
    hints: [
      `Estados 0/1/2: siga a ordem de descoberta ${JSON.stringify(dfsCycle.order)}.`,
      'Aresta de retorno aponta para um vértice em estado 1 (ainda "em progresso" na pilha de recursão).',
    ],
    solution: `DFS a partir de a: ordem ${dfsCycle.order.join(', ')}. A aresta c→a aponta de volta para "a", que ainda está em progresso (estado 1) — é a aresta de RETORNO, e indica o ciclo a→b→c→a.`,
  },
  {
    id: 'dfs-03',
    examFamily: 'ciclo-dfs-scc',
    topic: 'dfs-classificacao',
    difficulty: 'medium',
    duration: 'normal',
    examLikelihood: 'medium',
    sourceStyle: 'generated',
    type: 'ORDERING',
    prompt: 'Ordene os vértices pela ordem de DESCOBERTA (estado 0→1) de uma DFS a partir de "a" (prioridade alfabética).',
    displayGraphs: { a: DG_CYCLE },
    items: DG_CYCLE.vertices.map((v) => ({ id: v.id, label: v.label })).sort(() => Math.random() - 0.5),
    correctOrder: dfsCycle.order,
    source: { type: 'professor_board' },
    hints: [`Estados registrados: discovery=${JSON.stringify(dfsCycle.discovery)}.`],
    solution: `Ordem de descoberta: ${dfsCycle.order.join(' → ')}.`,
  },
  {
    id: 'fecho-01',
    examFamily: 'fecho-base-antibase',
    topic: 'fecho-transitivo',
    difficulty: 'medium',
    duration: 'normal',
    examLikelihood: 'high',
    sourceStyle: 'old_exam',
    type: 'GRAPH_SELECT_VERTEX',
    prompt: 'Selecione o fecho transitivo DIRETO do vértice "a" no grafo dirigido abaixo (todos os vértices alcançáveis a partir de a).',
    graph: DG_CYCLE,
    multi: true,
    correctVertexIds: transitiveClosureDirect(DG_CYCLE, 'a'),
    source: { type: 'old_exam', file: '2022-1-exam.pdf' },
    professorStyleSimilarity: 'high',
    hints: ['Faça uma DFS/BFS a partir de a e marque tudo que é alcançado (sem contar o próprio a).'],
    solution: `Γ⁺(a) = {${transitiveClosureDirect(DG_CYCLE, 'a').join(', ')}} — todo vértice alcançável a partir de a seguindo as arestas na direção original.`,
  },
  {
    id: 'fecho-02',
    examFamily: 'fecho-base-antibase',
    topic: 'fecho-transitivo',
    difficulty: 'hard',
    duration: 'normal',
    examLikelihood: 'high',
    sourceStyle: 'old_exam',
    type: 'GRAPH_SELECT_VERTEX',
    prompt: 'Selecione o fecho transitivo INVERSO do vértice "a" no mesmo grafo (todos os vértices que alcançam a).',
    graph: DG_CYCLE,
    multi: true,
    correctVertexIds: transitiveClosureInverse(DG_CYCLE, 'a'),
    source: { type: 'old_exam', file: '2022-1-exam.pdf' },
    professorStyleSimilarity: 'high',
    hints: ['Transponha o grafo (inverta todas as arestas) e refaça a busca a partir de a.'],
    solution: `Transpondo o grafo e buscando a partir de a: Γ⁺(a) no transposto = {${transitiveClosureInverse(DG_CYCLE, 'a').join(', ')}} — são os vértices que, no grafo original, alcançam a.`,
  },
  {
    id: 'base-01',
    examFamily: 'fecho-base-antibase',
    topic: 'base-antibase',
    difficulty: 'hard',
    duration: 'deep',
    examLikelihood: 'high',
    sourceStyle: 'old_exam',
    type: 'GRAPH_SELECT_VERTEX',
    prompt: 'Selecione os vértices que formam uma BASE do grafo dirigido abaixo (conjunto de cardinalidade mínima tal que todo vértice é alcançável a partir dele).',
    graph: PROFESSOR_SCC_EXAMPLE,
    multi: true,
    correctVertexIds: scc.base,
    source: { type: 'professor_support_material', file: 'Flash Cards Grafos-1.pdf' },
    professorStyleSimilarity: 'high',
    hints: [
      'Calcule os componentes fortemente conexos primeiro (contraia ciclos em hipervértices).',
      `Componentes deste grafo: ${JSON.stringify(scc.components)}.`,
      'Dentre os componentes, quais têm grau de entrada 0 na condensação (não são alcançados por nenhum outro componente)?',
    ],
    solution: `Componentes fortemente conexos: ${scc.components.map((c) => `{${c.join(',')}}`).join(', ')}. Os componentes {A} e {D,E} não são alcançados por nenhum outro — formam a base: {${scc.base.join(', ')}} (um representante de cada componente-fonte).`,
  },
  {
    id: 'base-02',
    examFamily: 'fecho-base-antibase',
    topic: 'base-antibase',
    difficulty: 'hard',
    duration: 'deep',
    examLikelihood: 'high',
    sourceStyle: 'old_exam',
    type: 'GRAPH_SELECT_VERTEX',
    prompt: 'No mesmo grafo, selecione os vértices que formam uma ANTI-BASE (todo vértice deve alcançar algum vértice da anti-base).',
    graph: PROFESSOR_SCC_EXAMPLE,
    multi: true,
    correctVertexIds: scc.antiBase,
    source: { type: 'professor_support_material', file: 'Flash Cards Grafos-1.pdf' },
    professorStyleSimilarity: 'high',
    hints: ['Anti-base = base do grafo TRANSPOSTO — procure os componentes-sumidouro (grau de saída 0 na condensação).'],
    solution: `Componentes-sumidouro (grau de saída 0 na condensação): a anti-base é {${scc.antiBase.join(', ')}}.`,
  },
  {
    id: 'base-03',
    examFamily: 'fecho-base-antibase',
    topic: 'base-antibase',
    difficulty: 'hard',
    duration: 'deep',
    examLikelihood: 'high',
    sourceStyle: 'old_exam',
    type: 'PROOF_OR_JUSTIFICATION',
    prompt: 'Como seria um algoritmo para identificar uma base em um grafo dirigido? Sua solução funciona para quais tipos de grafo?',
    rubric: [
      'Calcula o grau de entrada de todos os vértices',
      'Identifica vértices de grau de entrada 0 como candidatos naturais',
      'Trata o caso de ciclos: contrai cada ciclo (ou SCC) em um hipervértice antes de olhar grau de entrada',
      'Explica que um representante de cada SCC-fonte (grau de entrada 0 na condensação) compõe a base',
      'Discute a generalidade: funciona para qualquer grafo dirigido (com ou sem ciclo), pois a condensação em SCCs é sempre um DAG',
    ],
    source: { type: 'old_exam', file: '2022-1-exam.pdf' },
    professorStyleSimilarity: 'high',
    hints: [
      'Comece pelo caso sem ciclos: quais vértices nunca são "apontados" por ninguém?',
      'E se houver um ciclo? Um vértice dentro de um ciclo sempre tem grau de entrada ≥1 — como resolver isso?',
      'Pense em "encolher" o ciclo inteiro em um único vértice (isso é, essencialmente, calcular os SCCs).',
    ],
    solution:
      'Calcule o grau de entrada de todos os vértices. Vértices com grau de entrada 0 não são alcançados por ninguém e são candidatos à base. Se o grafo tem ciclos, isso sozinho não basta (todo vértice de um ciclo tem grau de entrada ≥1) — contraia cada componente fortemente conexo (SCC) em um hipervértice (equivalente à condensação do grafo). Como a condensação é sempre um DAG, agora sim: hipervértices com grau de entrada 0 correspondem às SCCs-fonte, e um representante de cada uma forma a base. Funciona para QUALQUER grafo dirigido, cíclico ou não — grafos sem ciclo são só o caso particular onde cada SCC é um único vértice.',
  },
  {
    id: 'ciclo-01',
    examFamily: 'ciclo-dfs-scc',
    topic: 'deteccao-ciclo',
    difficulty: 'medium',
    duration: 'quick',
    examLikelihood: 'high',
    sourceStyle: 'generated',
    type: 'TRUE_FALSE',
    prompt: 'Uma DFS que nunca encontra uma aresta de retorno (para um vértice em estado 1) prova que o grafo dirigido é acíclico.',
    correctValue: true,
    source: { type: 'professor_board' },
    hints: ['Pense na contrapositiva: se há um ciclo, a DFS necessariamente vai "voltar" a um vértice ainda em progresso em algum momento.'],
    solution: 'Correto — grafo dirigido é acíclico ⟺ nenhuma DFS a partir de qualquer vértice produz aresta de retorno. É o critério padrão de detecção de ciclo.',
  },
  {
    id: 'ciclo-02',
    examFamily: 'ciclo-dfs-scc',
    topic: 'deteccao-ciclo',
    difficulty: 'hard',
    duration: 'deep',
    examLikelihood: 'high',
    sourceStyle: 'old_exam',
    type: 'PROOF_OR_JUSTIFICATION',
    prompt: 'Apresente pelo menos DUAS estratégias diferentes para determinar se um grafo dirigido G possui algum ciclo.',
    rubric: [
      'Estratégia 1: DFS com estados 0/1/2, detectando aresta de retorno (destino em estado 1)',
      'Estratégia 2: tentativa de ordenação topológica por remoção incremental de grau de entrada 0 — se sobrar vértice, há ciclo',
      'Explica corretamente o critério de parada/detecção de cada estratégia',
      'Compara as duas abordagens (ambas O(V+E), mas mecanismos diferentes)',
    ],
    source: { type: 'old_exam', file: 'P1-TGC.pdf' },
    professorStyleSimilarity: 'high',
    hints: [
      'Estratégia 1 usa DFS diretamente — qual estado indica "ciclo encontrado"?',
      'Estratégia 2 usa ordenação topológica — o que acontece se o algoritmo não conseguir processar todos os vértices?',
    ],
    solution:
      'Estratégia 1 (DFS com estados): marque vértices com 0 (não visitado)/1 (em progresso)/2 (terminado); ao processar as arestas de um vértice em progresso, se alguma aponta para um vértice em estado 1, há ciclo. Estratégia 2 (ordenação topológica incremental): repita remover vértices de grau de entrada 0 (e suas arestas de saída); se ao final sobrar algum vértice sem nunca atingir grau de entrada 0, o grafo tem ciclo (não existe ordenação topológica válida). As duas rodam em O(V+E) e chegam à mesma conclusão por caminhos diferentes — a prova de 2026/1 pede exatamente essas duas abordagens.',
  },
];
