import type { Question } from '@/content/types';

// Sem provas antigas para verificar estas questões (conteúdo reordenado só
// neste semestre — ver docs/p1-scope.md). sourceStyle é 'slide' ou
// 'generated', nunca 'old_exam', e examLikelihood fica 'medium' (nunca
// 'high') porque não há amostra estatística real de que isso cai — só a
// evidência do cronograma de que é dado bem antes da prova.

export const logicaConjuntosQuestions: Question[] = [
  {
    id: 'conj-01',
    topic: 'teoria-de-conjuntos',
    difficulty: 'medium',
    duration: 'quick',
    examLikelihood: 'medium',
    sourceStyle: 'generated',
    type: 'TRUE_FALSE',
    prompt: 'Considerando A = {1, 2, 3}: a afirmação "{2} ∈ A" é verdadeira.',
    correctValue: false,
    source: { type: 'professor_slide', file: '03-graphs-set-theory.pdf' },
    hints: ['∈ é para ELEMENTOS, não para subconjuntos.', '2 ∈ A é verdadeiro. Mas {2} é um CONJUNTO — ele não é um dos elementos de A (os elementos de A são 1, 2 e 3, não o conjunto {2}).'],
    solution: 'Falso — {2} é um subconjunto de A ({2}⊆A), não um elemento de A. O elemento 2 (sem chaves) sim pertence a A: 2∈A.',
  },
  {
    id: 'conj-02',
    topic: 'teoria-de-conjuntos',
    difficulty: 'easy',
    duration: 'quick',
    examLikelihood: 'medium',
    sourceStyle: 'generated',
    type: 'NUMBER_INPUT',
    prompt: 'Se |A| = 5, quantos elementos tem o conjunto das partes P(A)?',
    correctNumber: 32,
    source: { type: 'professor_slide', file: '03-graphs-set-theory.pdf' },
    hints: ['|P(A)| = 2^|A|.'],
    solution: '|P(A)| = 2⁵ = 32 — cada elemento de A pode estar presente ou ausente em cada subconjunto, 2 escolhas por elemento.',
  },
  {
    id: 'conj-03',
    topic: 'teoria-de-conjuntos',
    difficulty: 'medium',
    duration: 'quick',
    examLikelihood: 'medium',
    sourceStyle: 'generated',
    type: 'MULTIPLE_CHOICE',
    prompt: 'Pela Lei de De Morgan para conjuntos, (A ∪ B)ᶜ é igual a:',
    options: [
      { id: 'a', label: 'Aᶜ ∩ Bᶜ' },
      { id: 'b', label: 'Aᶜ ∪ Bᶜ' },
      { id: 'c', label: 'A ∩ B' },
      { id: 'd', label: 'A ∪ B' },
    ],
    correctOptionId: 'a',
    source: { type: 'professor_slide', file: '03-graphs-set-theory.pdf' },
    hints: ['O complemento da união vira interseção dos complementos.'],
    solution: '(A∪B)ᶜ = Aᶜ∩Bᶜ. Analogamente, (A∩B)ᶜ = Aᶜ∪Bᶜ.',
  },
  {
    id: 'conj-04',
    topic: 'teoria-de-conjuntos',
    difficulty: 'medium',
    duration: 'quick',
    examLikelihood: 'medium',
    sourceStyle: 'generated',
    type: 'SHORT_ANSWER',
    prompt: 'Como se chama uma função f:A→B em que elementos distintos de A sempre têm imagens distintas em B?',
    acceptedAnswers: ['injetora', 'função injetora', 'injetiva'],
    source: { type: 'professor_slide', file: '03-graphs-set-theory.pdf' },
    hints: ['Não é sobre "cobrir" todo B — é sobre nunca repetir imagem.'],
    solution: 'Injetora (ou injetiva): x₁≠x₂ ⟹ f(x₁)≠f(x₂). Não confundir com sobrejetora (cobre todo o contradomínio) nem bijetora (as duas coisas).',
  },
  {
    id: 'conj-05',
    topic: 'teoria-de-conjuntos',
    difficulty: 'hard',
    duration: 'deep',
    examLikelihood: 'medium',
    sourceStyle: 'generated',
    type: 'PROOF_OR_JUSTIFICATION',
    prompt: 'Prove que a composição de duas funções injetoras é injetora. Ou seja: se f:A→B e g:B→C são injetoras, prove que (g∘f):A→C também é injetora.',
    rubric: [
      'Assume x₁, x₂ ∈ A com (g∘f)(x₁) = (g∘f)(x₂)',
      'Reescreve como g(f(x₁)) = g(f(x₂))',
      'Usa que g é injetora para concluir f(x₁) = f(x₂)',
      'Usa que f é injetora para concluir x₁ = x₂',
      'Conclui que (g∘f) é injetora',
    ],
    source: { type: 'professor_slide', file: '03-graphs-set-theory.pdf' },
    hints: [
      'Para provar injetividade, comece assumindo que as imagens são iguais e mostre que os elementos originais também precisam ser iguais.',
      '(g∘f)(x₁) = (g∘f)(x₂) significa g(f(x₁)) = g(f(x₂)) — o que a injetividade de g permite concluir daí?',
    ],
    solution:
      'Sejam x₁,x₂∈A com (g∘f)(x₁)=(g∘f)(x₂), ou seja, g(f(x₁))=g(f(x₂)). Como g é injetora, isso implica f(x₁)=f(x₂). Como f é injetora, isso implica x₁=x₂. Logo, (g∘f)(x₁)=(g∘f)(x₂) ⟹ x₁=x₂, que é exatamente a definição de (g∘f) ser injetora.',
  },
  {
    id: 'prop-01',
    topic: 'logica-proposicional',
    difficulty: 'medium',
    duration: 'quick',
    examLikelihood: 'medium',
    sourceStyle: 'generated',
    type: 'TRUE_FALSE',
    prompt: 'Se p é falsa, então p → q é sempre verdadeira, independentemente do valor de q.',
    correctValue: true,
    source: { type: 'professor_slide', file: '06-graphs-propositional-logic.pdf' },
    hints: ['p→q só é falsa em UM caso específico — qual?'],
    solution: 'Correto — p→q só é falsa quando p=V e q=F. Se p=F, a implicação é verdadeira ("vacuamente"), não importa o valor de q.',
  },
  {
    id: 'prop-02',
    topic: 'logica-proposicional',
    difficulty: 'easy',
    duration: 'quick',
    examLikelihood: 'medium',
    sourceStyle: 'generated',
    type: 'MULTIPLE_CHOICE',
    prompt: 'Com p = Verdadeiro e q = Falso, qual o valor de p → q?',
    options: [
      { id: 'a', label: 'Verdadeiro' },
      { id: 'b', label: 'Falso' },
    ],
    correctOptionId: 'b',
    source: { type: 'professor_slide', file: '06-graphs-propositional-logic.pdf' },
    hints: ['Este é exatamente o único caso em que a implicação é falsa.'],
    solution: 'Falso — p→q só é falsa quando a premissa (p) é verdadeira e a conclusão (q) é falsa. Este é exatamente esse caso.',
  },
  {
    id: 'prop-03',
    topic: 'logica-proposicional',
    difficulty: 'medium',
    duration: 'quick',
    examLikelihood: 'medium',
    sourceStyle: 'generated',
    type: 'SHORT_ANSWER',
    prompt: 'Escreva a contrapositiva de "p → q" (use ¬ para negação).',
    acceptedAnswers: ['¬q→¬p', '¬q → ¬p', 'not q -> not p', '~q->~p', '¬q⟹¬p'],
    source: { type: 'professor_slide', file: '06-graphs-propositional-logic.pdf' },
    hints: ['Contrapositiva: nega os dois termos E troca a ordem.'],
    solution: '¬q → ¬p — é a única das três variantes (recíproca q→p, inversa ¬p→¬q, contrapositiva ¬q→¬p) logicamente equivalente à implicação original.',
  },
  {
    id: 'prop-04',
    topic: 'logica-proposicional',
    difficulty: 'easy',
    duration: 'quick',
    examLikelihood: 'medium',
    sourceStyle: 'generated',
    type: 'MULTIPLE_CHOICE',
    prompt: '¬(p ∧ q) é logicamente equivalente a:',
    options: [
      { id: 'a', label: '¬p ∨ ¬q' },
      { id: 'b', label: '¬p ∧ ¬q' },
      { id: 'c', label: 'p ∨ q' },
      { id: 'd', label: 'p ∧ ¬q' },
    ],
    correctOptionId: 'a',
    source: { type: 'professor_slide', file: '06-graphs-propositional-logic.pdf' },
    hints: ['De Morgan para lógica proposicional: negar um "e" vira "ou" dos negados.'],
    solution: '¬(p∧q) ≡ ¬p∨¬q (De Morgan). Analogamente, ¬(p∨q) ≡ ¬p∧¬q.',
  },
  {
    id: 'prop-05',
    topic: 'logica-proposicional',
    difficulty: 'hard',
    duration: 'deep',
    examLikelihood: 'medium',
    sourceStyle: 'generated',
    type: 'PROOF_OR_JUSTIFICATION',
    prompt: 'Prove, construindo a tabela-verdade completa, que p → q é logicamente equivalente à sua contrapositiva ¬q → ¬p.',
    rubric: [
      'Constrói a tabela com as 4 combinações de p e q (VV, VF, FV, FF)',
      'Calcula corretamente p→q para cada linha',
      'Calcula corretamente ¬q→¬p para cada linha',
      'Mostra que as colunas finais são idênticas em todas as 4 linhas',
      'Conclui a equivalência lógica a partir da tabela idêntica',
    ],
    source: { type: 'professor_slide', file: '06-graphs-propositional-logic.pdf' },
    hints: ['Monte as 4 linhas de p e q, depois calcule cada implicação separadamente.', 'Lembre: implicação só é falsa no caso V→F.'],
    solution:
      'Tabela-verdade: (p=V,q=V): p→q=V, ¬q=F,¬p=F, ¬q→¬p=V. (p=V,q=F): p→q=F, ¬q=V,¬p=F, ¬q→¬p=F. (p=F,q=V): p→q=V, ¬q=F,¬p=V, ¬q→¬p=V. (p=F,q=F): p→q=V, ¬q=V,¬p=V, ¬q→¬p=V. As colunas de p→q e ¬q→¬p são idênticas nas 4 linhas (V,F,V,V) — logo são logicamente equivalentes.',
  },
  {
    id: 'pred-01',
    topic: 'logica-de-predicados',
    difficulty: 'medium',
    duration: 'quick',
    examLikelihood: 'medium',
    sourceStyle: 'generated',
    type: 'TRUE_FALSE',
    prompt: 'Para provar que ∀xP(x) é falso, basta encontrar UM único contraexemplo (um x para o qual P(x) é falso).',
    correctValue: true,
    source: { type: 'professor_slide', file: '07-graphs-predicate-logic.pdf' },
    hints: ['∀ exige que TODOS satisfaçam — um único que falhe já quebra a afirmação.'],
    solution: 'Correto — um único contraexemplo já é suficiente para falsear ∀xP(x), já que a afirmação exige que TODOS os elementos do domínio satisfaçam P.',
  },
  {
    id: 'pred-02',
    topic: 'logica-de-predicados',
    difficulty: 'medium',
    duration: 'quick',
    examLikelihood: 'medium',
    sourceStyle: 'generated',
    type: 'MULTIPLE_CHOICE',
    prompt: 'A negação de "∀x P(x)" é:',
    options: [
      { id: 'a', label: '∃x ¬P(x)' },
      { id: 'b', label: '∀x ¬P(x)' },
      { id: 'c', label: '∃x P(x)' },
      { id: 'd', label: '¬∃x P(x)' },
    ],
    correctOptionId: 'a',
    source: { type: 'professor_slide', file: '07-graphs-predicate-logic.pdf' },
    hints: ['"Não é verdade que todo x tem P" equivale a "existe algum x sem P".'],
    solution: '¬∀xP(x) ≡ ∃x¬P(x). Simetricamente, ¬∃xP(x) ≡ ∀x¬P(x).',
  },
  {
    id: 'pred-03',
    topic: 'logica-de-predicados',
    difficulty: 'medium',
    duration: 'quick',
    examLikelihood: 'medium',
    sourceStyle: 'generated',
    type: 'SHORT_ANSWER',
    prompt: 'Escreva a negação de "∃x P(x)" (use ∀ e ¬).',
    acceptedAnswers: ['∀x¬p(x)', '∀x ¬p(x)', 'forall x not p(x)', '∀x¬P(x)'],
    source: { type: 'professor_slide', file: '07-graphs-predicate-logic.pdf' },
    hints: ['Regra simétrica à negação de ∀.'],
    solution: '¬∃xP(x) ≡ ∀x¬P(x) — "não existe x com P" equivale a "todo x não tem P".',
  },
  {
    id: 'pred-04',
    topic: 'logica-de-predicados',
    difficulty: 'hard',
    duration: 'normal',
    examLikelihood: 'medium',
    sourceStyle: 'generated',
    type: 'TRUE_FALSE',
    prompt: 'A expressão "∀x (x é par ∧ x é primo)" está correta para representar a afirmação "todo número par é primo".',
    correctValue: false,
    source: { type: 'professor_slide', file: '07-graphs-predicate-logic.pdf' },
    hints: ['Com ∧ dentro de um ∀, você está afirmando que TODO x tem as duas propriedades ao mesmo tempo — não é isso que "todo par é primo" significa.'],
    solution:
      'Falso. "∀x (x é par ∧ x é primo)" diz que TODO número é par E primo simultaneamente — quase sempre falso e não é o que se quer dizer. A forma correta é "∀x (x é par → x é primo)": para todo x, SE x é par ENTÃO x é primo. A regra geral: use → (não ∧) para restringir o domínio dentro de um ∀.',
  },
  {
    id: 'pred-05',
    topic: 'logica-de-predicados',
    difficulty: 'hard',
    duration: 'deep',
    examLikelihood: 'medium',
    sourceStyle: 'generated',
    type: 'PROOF_OR_JUSTIFICATION',
    prompt:
      'Traduza para lógica de predicados a afirmação "Todo grafo simples com pelo menos 2 vértices possui dois vértices de mesmo grau" (a prova clássica por casa dos pombos vista no módulo de Fundamentos). Explique por que a tradução usa → e não ∧ ao restringir o quantificador ∀ ao caso "|V(G)|≥2".',
    rubric: [
      'Introduz um predicado para "G é um grafo simples com |V(G)|≥2" (a hipótese)',
      'Introduz um predicado para "G tem dois vértices de mesmo grau" (a conclusão)',
      'Monta a fórmula como ∀G (hipótese → conclusão), não ∀G (hipótese ∧ conclusão)',
      'Explica que ∧ afirmaria que TODO grafo satisfaz as duas propriedades ao mesmo tempo (inclusive grafos com 1 vértice, ou até "coisas" que não são grafos), enquanto → só faz a afirmação condicionalmente, para os grafos que de fato satisfazem a hipótese',
    ],
    source: { type: 'professor_slide', file: '07-graphs-predicate-logic.pdf' },
    professorStyleSimilarity: 'medium',
    hints: [
      'Defina H(G) = "G é grafo simples com |V(G)|≥2" e C(G) = "G tem dois vértices de mesmo grau".',
      'A afirmação é condicional: "SE G satisfaz a hipótese ENTÃO vale a conclusão" — que conectivo representa "se...então"?',
    ],
    solution:
      'Sejam H(G): "G é um grafo simples com |V(G)|≥2" e C(G): "G possui dois vértices de mesmo grau". A tradução correta é ∀G (H(G) → C(G)) — "para todo G, se G satisfaz a hipótese, então vale a conclusão". Usar ∧ no lugar (∀G (H(G) ∧ C(G))) afirmaria que TODO grafo do domínio (inclusive grafos de 1 vértice, ou grafos que não satisfazem a hipótese) tem as duas propriedades simultaneamente — o que é falso e não é o que o teorema diz. O padrão geral (o mesmo do tópico "Lógica de predicados"): restrição de domínio dentro de ∀ usa →, nunca ∧.',
  },
];
